feat(groups): break down groups/all page in smaller views
Elgg/Elgg pull request #10256
Opened 2016-09-23 16:51 UTC by hypeJunction

Make it easier to override individual parts and add new listing types
to the groups/all page

2016-09-23 17:10 UTC, jeabakker commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
why have this wrapper view in groups and not directly in discussions?

2016-09-23 17:11 UTC, jeabakker commented
I love the idea

2016-09-23 17:46 UTC, jdalsem commented on mod/groups/views/default/resources/groups/all.php
> +$content = elgg_view("groups/listing/$selecte_tab", $vars);
typo in selected tab

2016-09-23 18:08 UTC, hypeJunction commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
Saves adding exceptions to the resource view

2016-09-23 18:08 UTC, hypeJunction commented on mod/groups/views/default/resources/groups/all.php
> +$content = elgg_view("groups/listing/$selecte_tab", $vars);
Eh. Fixed locally. Didn't push I guess

2016-09-23 18:15 UTC, jeabakker commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
but in the resource view you check if the selected tab view exists. What exceptions are you revering to?

2016-09-23 18:24 UTC, juho-jaakkola approved these changes

2016-09-23 19:37 UTC, jdalsem requested changes
just the selected tab typo... then it is OK by me

2016-09-24 06:13 UTC, hypeJunction commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
It looks for `groups/listing/$selected_tab`

2016-09-24 06:15 UTC, hypeJunction commented
Typo is fixed

2016-09-24 06:25 UTC, jeabakker commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
excactly so this file can be in de discussions plugin, yes/no?

2016-09-24 06:27 UTC, hypeJunction commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
I see your point. I am not sure. I don't think I personally care either way.

2016-09-24 06:28 UTC, hypeJunction commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
I suppose we will be moving the tab registration over to the discussion plugin eventually, and we have this view in the groups plugin, we will be stuck with it. I will move to discussions.

2016-09-24 06:29 UTC, jeabakker commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
thx ;)

2016-09-24 06:32 UTC, hypeJunction commented on mod/groups/views/default/groups/listing/discussion.php
> +<?php
Done

2016-09-24 10:39 UTC, mrclay approved these changes

2016-09-24 10:39 UTC, merged