fix(groups): Group membership request check existing requests
Elgg/Elgg pull request #10277
Opened 2016-09-24 12:14 UTC by lowfill

Added check of exisiting request and added error message when an existing request exists

Fixes: #8901

2016-09-24 12:28 UTC, hypeJunction commented on mod/groups/actions/groups/membership/join.php
> +		if(!check_entity_relationship($user->guid,'membership_request',$group->guid)){
We prefer early termination:
```
if () {

} else if (check_entity_relationship()) {
   register_error();
   forward(REFERRER);
} else {

}
```

2016-09-24 12:29 UTC, hypeJunction commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You alredy requested join this group, please wait the group owner to respond.',
`You have already requested to join this group`, should be enough.

2016-09-24 12:35 UTC, mrclay commented on mod/groups/actions/groups/membership/join.php
> -		add_entity_relationship($user->guid, 'membership_request', $group->guid);
Instead use a return early strategy, which (in addition to other benefits) makes the diff cleaner to read. E.g.

```php
if (check_entity_relationship($user->guid, 'membership_request', $group->guid)) {
	register_error(elgg_echo("groups:requestexists"));
	forward(REFERER);
}
```

Also we enforce a [code style](http://learn.elgg.org/en/stable/contribute/code.html#php-guidelines) close to PSR-2. The Travis build will tell you if you get it wrong.

2016-09-24 12:36 UTC, mrclay commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You alredy requested join this group, please wait the group owner to respond.',
`You already requested to join this group. Please wait for the group owner to respond.`

2016-09-24 12:37 UTC, mrclay requested changes

2016-09-24 12:39 UTC, mrclay commented
Oops, 2 reviews saying same thing :)

2016-09-24 12:39 UTC, mrclay commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You alredy requested join this group, please wait the group owner to respond.',
Agreed.

2016-09-24 13:01 UTC, mrclay commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You alredy requested join this group.',
`You already requested to join this group.`

2016-09-24 13:03 UTC, mrclay commented on mod/groups/actions/groups/membership/join.php
> +	} else if(check_entity_relationship($user->guid,'membership_request',$group->guid)) {
- space after `if` (not a function call)
- space after each `,` in argument list
- `} else {`, not Drupal style

2016-09-24 13:05 UTC, lowfill commented
I don't understand was Travis is saying

2016-09-24 13:13 UTC, mrclay commented
See https://gitter.im/Elgg/Elgg?at=57e67afe00df3cc4224173dc

2016-09-27 09:04 UTC, jdalsem commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You alredy requested join this group, please wait the group owner to respond.',
typo in alredy..

2016-09-27 12:17 UTC, mrclay commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You already requested join this group.',
"requested **to** join"

2016-09-27 12:18 UTC, hypeJunction commented on mod/groups/languages/en.php
> +	'groups:requestexists' => 'You already requested join this group.',
I think proper English is `You have already requested` if no time is specified. Past tense is used if you specify time `You requested to joint his group 2 days ago`.

2016-10-07 06:51 UTC, hypeJunction commented
@lowfill Thanks for your contribution. I have used it as a basis for a different pull request here: #10379 10379

2016-10-07 06:51 UTC, closed without merging