feat(developers): explorer entity information in developer tools
Elgg/Elgg pull request #10318
Opened 2016-09-30 11:10 UTC by jdalsem

With the developer tools you can now lookup attributes, metadata,
relationships and private settings of entities. You can also remove
individual metadata, relationships or private settings for an entity or
remove an entity completely.

fixes #9384 

![entity_explorer](https://cloud.githubusercontent.com/assets/861833/18989963/3f757872-870f-11e6-9d9d-abb33b106291.png)

2016-09-30 12:09 UTC, hypeJunction reviewed
In hypeDBExplorer (https://github.com/hypejunction/hypedbexplorer) I also have subgrids for metadata owned by the entities, entity annotations and annotations owned, entities owned and contained by the entity, access collections owned by the entity, access collections the entity is member of, river items that the entity is subject/object/target of

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/actions/developers/entity_explorer_delete.php
> +	forward(REFERER);
We should start using response objects for new actions.
`return elgg_error_response()`

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +$entity_rows = ['type', 'subtype', 'owner_guid', 'site_guid', 'container_guid', 'access_id', 'time_created', 'time_updated', 'last_action', 'enabled'];
Should we add a static method to `ElggEntity` to get those from there?

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +echo elgg_view_module('inline', elgg_echo('developers:entity_explorer:info:attributes'), $entity_info);
One module - one view. Makes it easier to read and modify.

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +			'href' => 'action/developers/entity_explorer_delete?guid=' . $entity->guid . '&type=metadata&key=' . $md->name,
Use `elgg_http_add_url_query_elements()`

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +	$relationship_columns = ['id', 'time_created', 'guid_one', 'relationship', 'guid_two'];
Make `guid_one` and `guid_two` links that open a new tab/ligthbox with Entity explorer for that entity

2016-09-30 12:09 UTC, hypeJunction commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +$entity_metadata = elgg_get_metadata(['guid' => $guid, 'limit' => false]);
We should probably use `elgg_list_*` where possible with proper offset keys, in case these get too much on a large site.

2016-10-01 02:39 UTC, mrclay commented
I think non-tech admins could really wreck things with this. I wouldn't mind requiring a setting be checked to enable editing, with a big red warning. And a hook to override so sites could decide who can edit. But I'm paranoid.

2016-10-01 02:43 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +	$relationship_columns = ['id', 'time_created', 'guid_one', 'relationship', 'guid_two'];
Cool but can wait

2016-10-03 19:42 UTC, jdalsem commented
> subgrids for metadata owned by the entities, entity annotations and annotations owned, entities owned and contained by the entity, access collections owned by the entity, access collections the entity is member of, river items that the entity is subject/object/target of

i was trying to add a basic feature for debugging... dbexplorer brings way more features... like it, but may be a bit too much for core...

> I think non-tech admins could really wreck things with this.

it is developer tools... i do not expect non-tech to use it a lot.

> And a hook to override so sites could decide who can edit.

can always make a view_var hook to quick return if you want to limit it....

2016-10-03 19:42 UTC, jdalsem commented on mod/developers/actions/developers/entity_explorer_delete.php
> +	forward(REFERER);
done

2016-10-03 19:42 UTC, jdalsem commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +$entity_rows = ['type', 'subtype', 'owner_guid', 'site_guid', 'container_guid', 'access_id', 'time_created', 'time_updated', 'last_action', 'enabled'];
meh... maybe later... schema is being overhauled... could add it later on...

2016-10-03 19:42 UTC, jdalsem commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +echo elgg_view_module('inline', elgg_echo('developers:entity_explorer:info:attributes'), $entity_info);
done

2016-10-03 19:42 UTC, jdalsem commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +			'href' => 'action/developers/entity_explorer_delete?guid=' . $entity->guid . '&type=metadata&key=' . $md->name,
done

2016-10-03 19:43 UTC, jdalsem commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +	$relationship_columns = ['id', 'time_created', 'guid_one', 'relationship', 'guid_two'];
will wait...

2016-10-03 19:43 UTC, jdalsem commented on mod/developers/views/default/admin/develop_tools/entity_explorer.php
> +$entity_metadata = elgg_get_metadata(['guid' => $guid, 'limit' => false]);
metadata is manageable... offsets makes it more complex... you will just have to wait a few secs longer

2016-10-03 19:45 UTC, jdalsem commented
hoping this can go in in current state... if you see need for improvements you can always add a PR for it

2016-10-04 01:13 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/attributes.php
> +$entity_rows = ['type', 'subtype', 'owner_guid', 'site_guid', 'container_guid', 'access_id', 'time_created', 'time_updated', 'last_action', 'enabled'];
Entities are iterators:
```php
foreach ($entity as $attr => $value) {
    // just need to strip password_hash, password, and salt.
}
```

2016-10-04 01:15 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/attributes.php
> +	$entity_info .= '<td>' . $entity_row . '</td><td>' . $entity->$entity_row . '</td>';
Needs `htmlspecialchars(..., ENT_QUOTES)`

2016-10-04 01:17 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/metadata.php
> +	$md_columns = ['id', 'name_id', 'name', 'value_id', 'value', 'value_type', 'access_id', 'time_created', 'enabled'];
ElggMetadata iterate their attributes, too.

2016-10-04 01:18 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/metadata.php
> +		$metadata_info .= '<th>' . $md_col . '</th>';
htmlspecialchars like above.

2016-10-04 01:18 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/metadata.php
> +			$metadata_info .= '<td>' . $md->$md_col . '</td>';
And here...

2016-10-04 01:19 UTC, mrclay commented on mod/developers/views/default/admin/develop_tools/entity_explorer/private_settings.php
> +		$private_settings_info .= "<td>$key</td><td>$value</td>";
HTML escape both

2016-10-04 01:23 UTC, mrclay requested changes
HTML escaping is a must. Reworking to use iterators (for everything) to get attributes/values can wait.

2016-10-04 12:43 UTC, mrclay commented
I suppose filter_tags() would be OK instead of escaping.

2016-10-04 14:52 UTC, jdalsem commented
i think going for output/text is more the elgg way

2016-10-07 09:18 UTC, jdalsem commented
now using output/text, so html is escaped where needed

2016-10-08 17:13 UTC, mrclay approved these changes

2016-10-10 06:42 UTC, merged