feat(core): reworked the walledgarden layout
Elgg/Elgg pull request #10370
Opened 2016-10-05 09:40 UTC by jdalsem

Most notable changes
- different look and feel
- dropped the javascript form loading behaviour (including the helper views for ajax loaded forms)
- dropped the walledgarden rounded corners images
- reduced the need for custom css in themes related to walled garden
- moved walled garden css loading to page shell (so no need to load it whereever you draw the walled garden)
- simplyfied and standardized usage of walled_garden pageshell/layout/module

Background Image used is CC0 Public Domain https://pixabay.com/en/lamp-jetty-wooden-pier-banister-677698/

Themes can easily replace the background image by adding the view /walled_garden.jpg

![walled garden](https://cloud.githubusercontent.com/assets/861833/19108166/f1989df2-8aef-11e6-9be9-0f12b93c68c2.png)

2016-10-05 11:46 UTC, mrclay commented on views/default/page/walled_garden.php
I wonder if we render some other view to reduce duplication here. Maybe not.

2016-10-07 05:48 UTC, hypeJunction requested changes

2016-10-07 05:48 UTC, hypeJunction commented on mod/externalpages/views/default/expages/wrapper.php
>  echo '<div class="mtm">';
Make this a clearfix

2016-10-07 05:48 UTC, hypeJunction commented on mod/externalpages/start.php
> +		'content' => elgg_view('output/longtext', ['value' => $description]),
Could you break this down into multiple lines, please

2016-10-07 05:48 UTC, hypeJunction commented on mod/externalpages/start.php
>  		$body = elgg_view_layout('one_column', array('title' => $title, 'content' => $content));
```
$layout = 'default';
if (elgg_get_config('walled_garden') && !elgg_is_logged_in()) {
   $layout = 'walled_garden';
}
$body = elgg_view_layout($layout, [
   'title' => $title,
   'content' => $content,
   'sidebar' => false, // or?
]);
```

2016-10-07 05:48 UTC, hypeJunction commented on views/default/forms/user/changepassword.php
> +echo elgg_view('output/longtext', ['value' => elgg_echo('user:changepassword:change_password_confirm')]);
Break down into multiple lines

2016-10-07 05:48 UTC, hypeJunction commented on views/default/forms/user/changepassword.php
> +echo elgg_view_input('hidden', [
Update to `elgg_view_filed()` unless it hasn't been yet

2016-10-07 05:48 UTC, hypeJunction commented on views/default/forms/user/changepassword.php
> +$footer = elgg_view('input/submit', ['value' => elgg_echo('changepassword')]);
`elgg_view_field()`

2016-10-07 05:48 UTC, hypeJunction commented on views/default/forms/user/requestnewpassword.php
> +$footer = elgg_view('input/submit', array('value' => elgg_echo('request')));
`elgg_view_field()`

2016-10-07 05:48 UTC, hypeJunction commented on views/default/page/layouts/walled_garden.php
> +echo elgg_view_module('walled_garden', $title, $body);
Is this needed? We are passing `title` to layout view

2016-10-07 05:48 UTC, hypeJunction commented on views/default/page/walled_garden.php
I think using the default shell should be fine

2016-10-07 05:48 UTC, hypeJunction commented on views/default/resources/account/change_password.php
>  	$body = elgg_view_layout('walled_garden', array('content' => $content));
I think we should just pass the title into the layout and get rid of walled garden module wrapper.

2016-10-07 05:48 UTC, hypeJunction commented on views/default/resources/account/forgotten_password.php
> +$content = elgg_view_form('user/requestnewpassword', ['class' => 'elgg-form-account']);
Pass the `$vars` to the form

2016-10-07 05:48 UTC, hypeJunction commented on views/default/walled_garden.css.php
> +	background-image: url('<?php echo elgg_get_simplecache_url('walled_garden.jpg'); ?>');
We don't really need to use php for this. 
`background-image: url(walled_garden.jpg);`

2016-10-07 05:48 UTC, hypeJunction commented on views/default/walled_garden.css.php
> +	background-image: url('<?php echo elgg_get_simplecache_url('walled_garden.jpg'); ?>');
I want to eventually make these proper .css files - there is not reason for all the hacky `<style>` declarations.

2016-10-07 05:48 UTC, hypeJunction commented on views/default/walled_garden.css.php
> +	width: 500px;
Do we need both `float` and `right`?

2016-10-07 06:53 UTC, jdalsem commented on views/default/forms/user/changepassword.php
> +echo elgg_view_input('hidden', [
was not available in master at that time...

2016-10-07 06:54 UTC, jdalsem commented on views/default/resources/account/change_password.php
>  	$body = elgg_view_layout('walled_garden', array('content' => $content));
so passing title to layout would draw a title (just as the regular shell does) and completely drop the walled garden module as it is just normal content? all up for it 👍

2016-10-07 06:55 UTC, jdalsem commented on views/default/walled_garden.css.php
> +	background-image: url('<?php echo elgg_get_simplecache_url('walled_garden.jpg'); ?>');
this php was the only thing not making them proper css files, so if i change the link, i will also change the file extension

2016-10-07 07:01 UTC, hypeJunction commented on views/default/walled_garden.css.php
> +	background-image: url('<?php echo elgg_get_simplecache_url('walled_garden.jpg'); ?>');
👏

2016-10-07 07:02 UTC, hypeJunction commented on views/default/forms/user/changepassword.php
> +echo elgg_view_input('hidden', [
I am going to merge up now

2016-10-07 08:09 UTC, jdalsem commented on views/default/walled_garden.css.php
> +	width: 500px;
nope

2016-10-07 08:21 UTC, jdalsem commented on views/default/page/walled_garden.php
don't think so... walled garden shell is a lot different then default shell

2016-10-07 10:18 UTC, hypeJunction commented on views/default/forms/user/changepassword.php
> +echo elgg_view_input('hidden', [
All branches are up to date now.

2016-10-08 20:36 UTC, mrclay commented on views/default/walled_garden.css
> +	background-image: url('walled_garden.jpg');
This only allows replacement with other JPGs. #8721 Not a blocking issue though.

2016-10-11 21:32 UTC, jdalsem commented
Addressed all comments; most notable changes:
- using default layout, no more walled garden layout, only walledgarden shell
- no more walled garden modules
- using elgg_view_field for forms

as far as i can see this is ready for a merge...

2016-10-12 03:02 UTC, mrclay commented
On register page, short viewports push the .elgg-page-footer menu into the register button.

2016-10-12 03:06 UTC, merged