feat(entities): get_entity() can now fetch entities with ignored access
Elgg/Elgg pull request #10379
Opened 2016-10-07 06:50 UTC by hypeJunction

`get_entity()` now accepts a second argument which allows fetching entities with ignored access. This reduces the boilerplate with `elgg_set_ignored_access()` as well as eliminates risk of plugins not
restoring the previous access bypass setting.

Also refactors the groups/join action for improved readability, adds a check to ensure that membership request does not exist before trying to create a new one.

Fixes #8901

2016-10-07 06:53 UTC, hypeJunction commented on mod/groups/actions/groups/membership/join.php
> +$user = get_entity($user_guid, true);
FYI, we should stop assuming that user entities are always accessible. I have implemented a few crazy access hacks on several projects that make user entities invisible until certain conditions are met.

2016-10-07 07:04 UTC, hypeJunction commented on engine/tests/ElggCoreGetEntitiesTest.php
> +		$this->assertIdentical($object, get_entity($object->guid));
Blah, simpletest doesn't compare objects well...

2016-10-07 07:16 UTC, hypeJunction commented
@mrclay Could you take a look at the test. I am out of the loop on simpletests and have no clue what the deal is with access controls there...

2016-10-08 02:50 UTC, mrclay commented
Not crazy about this.

- Makes easier to bypass access. This has cons
- 2nd argument usage doesn't look like anything potentially dangerous is being done.

`get_entity(123, ELGG_IGNORE_ACCESS)` would be a little better.

2016-10-08 02:54 UTC, mrclay commented
I've also considered `elgg_ignoring_access($func)` which would apply this pattern to an arbitrary function.

2016-10-08 07:01 UTC, beck24 commented
I think it's more common to get a range of entities than just one specific entity, if going this route having egef* functions with an ignore access option that applies this pattern would be useful.  But then I usually have to *do* something with them that still requires ignored access, so it's not really reducing the boilerplate that much.

2016-10-08 07:57 UTC, iionly commented
> But then I usually have to do something with them that still requires ignored access, so it's not really reducing the boilerplate that much.

Yep. What would be the use case to igonore access only for fetching the entity?

If second parameter is added for ignoring access, what about a 3rd parameter for hidden entities?

2016-10-08 17:02 UTC, mrclay commented
```php
$result = elgg_ignoring_access(function () use ($guid) {
  $entity = get_entity($guid);
  // do more stuff
  return $result;
});
```

At least with this pattern you can catch exceptions and make sure access gets turned back on. Using `elgg_set_ignore_access()` an exception can escape the scope leaving access off.

2016-10-11 09:40 UTC, jeabakker requested changes
I'm not a fan of having the 2 completely unrelated changes in one commit. At least have the 2 changes in separate commits. even better would be in 2 PR's so the changes can be discusses separately

2016-10-11 09:43 UTC, closed without merging

2016-10-11 09:43 UTC, hypeJunction commented
Not high on my priority list.