Admin username change
Elgg/Elgg pull request #10421
Opened 2016-10-11 13:39 UTC by jdalsem

This feature is admin only

![username1](https://cloud.githubusercontent.com/assets/861833/19272430/d6cba342-8fc8-11e6-96bd-007edfced05a.png)

 after toggle

![username2](https://cloud.githubusercontent.com/assets/861833/19272433/dc261930-8fc8-11e6-9838-d3636aff4f59.png)

@hypeJunction please check the changes in elgg_view_field... it fixes 2 issues with it:
- passing class ends up in field wrapper (should only be in input_vars)
- passing #class is changed to field_class but is not used in field wrapper

This change will also allow to pass all kinds of attributes to the field wrapper by using hashes as prefix

2016-10-11 14:47 UTC, hypeJunction reviewed
I don't see a compelling use case to pass more parameters to the field. It opens up doors for plugina to do hacky things and we end up with field mess again. I'd rather we be opinionated.

2016-10-11 14:47 UTC, hypeJunction commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
What does this do?

2016-10-11 14:50 UTC, jdalsem commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
it disables the slide animation and just toggles the visibility

2016-10-11 14:50 UTC, jdalsem commented
> I don't see a compelling use case to pass more parameters to the field. It opens up doors for plugina to do hacky things and we end up with field mess again. I'd rather we be opinionated.

this way i can not toggle fields visibility for example

2016-10-11 15:01 UTC, hypeJunction commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
Ah, the crazy toggler API. Any reason why you wouldn't want to just display the field?

2016-10-11 15:03 UTC, hypeJunction commented
Let's rework the toggler to use CSS transitions.

2016-10-11 15:05 UTC, hypeJunction commented on views/default/core/settings/account/username.php
> +	'#class' => 'hidden account-username-change',
We should allow `#id` though, and use that as the toggler selector. Me no like using toggling by class name

2016-10-11 15:06 UTC, jdalsem commented on views/default/core/settings/account/username.php
> +	'#class' => 'hidden account-username-change',
that is what i am doing here... hiding the button... showing the field

2016-10-11 15:10 UTC, jdalsem commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
wanted to make changing the username a more 'special'... like the danger zone (https://github.com/Elgg/Elgg/settings)

don't want an accidental change

2016-10-11 15:10 UTC, jdalsem commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
but if we think admins are sane enough (and they can always change it back)... we could do without the toggler

2016-10-11 15:24 UTC, hypeJunction commented on views/default/core/settings/account/username.php
> +	'#data-toggle-slide' => '0',
You could make it `special` by loading a separate form in a lightbox and not mix it with user settings.

2016-10-12 12:00 UTC, jdalsem commented
Updated the PR
- no longer does things that toggle

2016-10-12 21:24 UTC, jdalsem commented
should i rebase this for 2.x or keep it on master?

2016-10-12 23:30 UTC, mrclay commented
I'd prefer a separate action for this as I can imagine sites wanting to limit its use. A lightbox form sounds good.

2016-10-12 23:35 UTC, mrclay commented
Store an annotation with JSON: previous username, time changed, user who changed. Firing a hook also good idea. Too bad events don't have params so we could pass this stuff.

2016-10-13 09:20 UTC, jdalsem commented
> I'd prefer a separate action for this as I can imagine sites wanting to limit its use.

will be doing this in a separate PR (refactoring more of the usersettings forms)



> Store an annotation with JSON: previous username, time changed, user who changed. Firing a hook also good idea. Too bad events don't have params so we could pass this stuff.

i think all this info is already in system_log

2016-10-13 09:37 UTC, jeabakker requested changes

2016-10-13 09:37 UTC, jeabakker commented on engine/lib/user_settings.php
> +	if (!$user->canEdit()) {
what would be the use case that an admin is logged in and he can't edit the user?

2016-10-13 09:37 UTC, jeabakker commented on engine/lib/user_settings.php
> +	if ($user->username == $username) {
for PHP reasons ```$user->username === $username```

2016-10-13 09:46 UTC, jdalsem commented on engine/lib/user_settings.php
> +	if ($user->username == $username) {
fixed

2016-10-13 09:46 UTC, jdalsem commented on engine/lib/user_settings.php
> +	if (!$user->canEdit()) {
fixed

2016-10-13 10:38 UTC, jeabakker approved these changes

2016-10-13 10:38 UTC, merged