fix(core): parse_url no longer does a double parse
Elgg/Elgg pull request #10493
Opened 2016-10-19 14:42 UTC by jdalsem

fixes #8490 and fixes #6695

2016-10-19 15:11 UTC, jeabakker approved these changes

2016-10-19 15:37 UTC, hypeJunction requested changes

2016-10-19 15:37 UTC, hypeJunction commented on engine/tests/ElggCoreRegressionBugsTest.php
> +			'already anchor with link text <a href="http://twitter.com/">http://twitter.com</a> test' =>
We need to make sure that regex is not greedy. Needs a test with more than one anchor tag. Maybe a mix of diffetent tags. And an anchor tag within another tag.

2016-10-19 15:37 UTC, hypeJunction commented on engine/tests/ElggCoreRegressionBugsTest.php
> +			'already anchor with link text <a href="http://twitter.com/">http://twitter.com</a> test' =>
Twitter has a ljnkify library we many iseful test cases. Take a peek.

2016-10-20 10:27 UTC, jdalsem commented
working on a new PR

2016-10-20 10:27 UTC, closed without merging

2016-10-20 10:29 UTC, hypeJunction commented
I am yet to write tests, but take a look if you need inspiration: https://github.com/hypeJunction/hypeScraper/blob/master/classes/hypeJunction/Scraper/Linkify.php