chore(core): removed support for class parameter in elgg_instanceof
Elgg/Elgg pull request #10525
Opened 2016-10-26 06:59 UTC by jdalsem

fixes #6230

BREAKING CHANGE:
If you rely on a class check for your content, please use the PHP
instanceof type operator

2016-10-26 14:13 UTC, jeabakker requested changes

2016-10-26 14:13 UTC, jeabakker commented on mod/legacy_urls/start.php
> +		if (elgg_instanceof($group, 'group', '')) {
3rd param can also be removed as it isn't check in `elgg_instanceof` if it's empty

2016-10-27 11:42 UTC, jdalsem commented
addressed @jeabakker s comment

2016-10-29 03:10 UTC, mrclay commented on engine/lib/entities.php
> -	if ($class) {
Since we didn't deprecate this, what do you think about logging an error if `func_num_args() > 3`?

2016-10-31 10:29 UTC, jdalsem commented on engine/lib/entities.php
> -	if ($class) {
hmm... it is hardly ever used + it is 3.0, so we can...

2016-10-31 16:01 UTC, jeabakker approved these changes

2016-11-01 09:57 UTC, merged