feat(widgets): adding widgets now opens in a lightbox with more info
Elgg/Elgg pull request #10537
Opened 2016-10-28 13:40 UTC by jdalsem

fixes #9513

![add_widgets_in_lightbox](https://cloud.githubusercontent.com/assets/861833/19808329/ab4cd4ca-9d24-11e6-8534-17dab17563ac.png)

- [ ] Write / Update docs
- [ ] Test default widgets
- [ ] Fix admin css

2016-10-28 13:42 UTC, jdalsem commented
Should i separate widgets css in a separate file... so we can use it in frontend en admin? I think YES

I think i will also refactor the rest of the widgets js, so there will be no more `elgg/widgets`...

2016-10-28 15:10 UTC, jdalsem commented
changed some more to make the widget layout make more sense...

I had to change somethings in the dashboard and profile plugin for it to work again... passing content to the widget layout is no longer supported... there is a special 'no_widgets' parameter to echo a string or Closure if no widgets are present.

Dashboard uses the 'no widgets' parameter for the blurb, so you only see the intro text if there are no widgets.

Profile can no longer pass the wrapper view as content, so instead of making the profile details part of the widget layout, i set it on top of the widget layout. Also switched to a 2 column layout (BC with 3 column layout, by failing over widgets that are over the max columns into the last visible one).

2016-10-28 15:10 UTC, jdalsem commented
see screenshot in the initial post about the profile page changes

2016-10-28 15:42 UTC, hypeJunction commented
Are widgets columns in the nornal left to right order?

2016-10-28 15:43 UTC, hypeJunction commented
Let's just add owner block to prpfile pages and not do crazy stuff with user hover.

2016-10-28 15:52 UTC, jdalsem commented
Did not change widget column order,  so column 1 is still the right most column

2016-10-28 15:54 UTC, jdalsem commented
U faked the profile screenshot a bit. Was not planning on touching more if the profile wrapper... We could improve in the layout after this change

2016-10-28 15:58 UTC, hypeJunction commented
> Did not change widget column order, so column 1 is still the right most column

IMO, we should just swap. The only reason it's the other way around is because of the content wrapper that was there.

> Was not planning on touching more if the profile wrapper... We could improve in the layout after this change

Just a suggestion. We can do it later.

2016-10-28 16:06 UTC, jdalsem commented
Swapping the columns would cause a lot of issues... Only way to prevent it is to make some crazy migrate script...

2016-10-28 16:17 UTC, hypeJunction requested changes

2016-10-28 16:17 UTC, hypeJunction commented on mod/profile/views/default/profile/layout.php
> +echo elgg_view_layout('widgets', ['num_columns' => 2]);
Pass owner explicitly, chain from resource view if needed. Enough of this page owner magic.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets.php
> +$widget_class = "elgg-col-1of{$num_columns}";
Let's get rid of these and use flexbox.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets.php
> +		if (!array_key_exists($widget->handler, $widget_types)) {
Can this be done in ege* for widgets?

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets.php
> +			'elgg-widgets',
`elgg-widgets-column` ideally.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets.php
> +$result .= elgg_view('graphics/ajax_loader', ['id' => 'elgg-widget-loader']);
Get rid of this and use spinner.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_button.php
> +		'onclick' => 'require(["page/layouts/widgets/add_panel"])',
Make this a menu item and pass with `items` to `elgg_view_menu('title:widgets')` ? Use menu class instead of `elgg-widgets-add-control`

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.js
> +		var multiple = $item.attr('class').indexOf('elgg-widget-multiple') != -1;
`!$item.is('.elgg-widget-multiple')`

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.js
> +		elgg.get($(this).attr('href'), {
switch to `elgg/Ajax`

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +	echo elgg_echo('ajax:not_is_xhr');
log error instead?

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> - *
Why remove these?

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +elgg_set_page_owner_guid($owner_guid);
Make this view into a properly handled page with `elgg_ajax_gatekeeper()`. Setting page owner in views makes me icky.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +	$item_content = '<div class="elgg-widgets-add-actions float-alt">';
Can we do this without floats please?

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +		$item_content .= elgg_format_element('span', ['class' => 'elgg-quiet'], elgg_echo('widget:unavailable'));
Too long

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +	$item_content = '<div class="elgg-widgets-add-actions float-alt">';
Make it into a menu and float it with CSS if needed. I just don't want any more inline helper class uses. Makes it impossible for other plugin to work with without replacing the view.

2016-10-28 16:17 UTC, hypeJunction commented on views/default/page/layouts/widgets/add_panel.php
> +	$item_content .= "<h3>{$widget_type->name}</h3>";
Why `h3`? We should really audit our usages of headings, really bad for SEO.

2016-10-28 16:18 UTC, hypeJunction commented
> Swapping the columns would cause a lot of issues..

Such as?

2016-10-28 16:22 UTC, jdalsem commented
Them being in the wrong order... 

Btw... Nice review

2016-10-28 16:26 UTC, hypeJunction commented
If you ask me, that's the correct order. RTL site can swap them if it needs to.

2016-10-31 14:28 UTC, jdalsem commented on mod/profile/views/default/profile/layout.php
> +echo elgg_view_layout('widgets', ['num_columns' => 2]);
done

2016-10-31 14:30 UTC, jdalsem commented on views/default/page/layouts/widgets.php
> +		if (!array_key_exists($widget->handler, $widget_types)) {
thought about this myself too... not doing this for now... `elgg_get_widget_types` has support for exact match, don't want to burden `elgg_get_widgets` with that logic... letting the layout decide this for now... going to do a follow up to remove registering widgets for 'all' context and will remove the exact match then... makes it easier to do a valid handler check in `elgg_get_widgets`

2016-10-31 14:31 UTC, jdalsem commented on views/default/page/layouts/widgets.php
> +			'elgg-widgets',
not changing this for now

2016-10-31 14:31 UTC, jdalsem commented on views/default/page/layouts/widgets/add_button.php
> +		'onclick' => 'require(["page/layouts/widgets/add_panel"])',
done

2016-10-31 14:31 UTC, jdalsem commented on views/default/page/layouts/widgets.php
> +$result .= elgg_view('graphics/ajax_loader', ['id' => 'elgg-widget-loader']);
leaving this for now...

2016-10-31 14:31 UTC, jdalsem commented on views/default/page/layouts/widgets/add_panel.js
> +		var multiple = $item.attr('class').indexOf('elgg-widget-multiple') != -1;
done

2016-10-31 14:31 UTC, jdalsem commented on views/default/page/layouts/widgets/add_panel.js
> +		elgg.get($(this).attr('href'), {
done

2016-10-31 14:32 UTC, jdalsem commented on views/default/page/layouts/widgets/add_panel.php
> +	$item_content .= "<h3>{$widget_type->name}</h3>";
changed to h4 (as module heading is already h3).... but should module heading not be a h2?... other discussion

2016-10-31 14:36 UTC, jdalsem commented on views/default/page/layouts/widgets.php
> +$widget_class = "elgg-col-1of{$num_columns}";
changing the classes will break to much (in WidgetManager for example)...

2016-10-31 14:56 UTC, jdalsem commented on views/default/page/layouts/widgets/add_panel.php
> +elgg_set_page_owner_guid($owner_guid);
moved to a pagehandler

2016-10-31 15:20 UTC, jdalsem commented on views/default/page/layouts/widgets/add_panel.php
> +	$item_content = '<div class="elgg-widgets-add-actions float-alt">';
moved the float to the css... not making it a menu as it complexes the code needlessly combined with the status text about not being able to add multiple...

2016-10-31 16:12 UTC, jdalsem commented
addressed most of the comments by @hypeJunction 

hoping for a merger... can do follow ups for semi related stuff (that remained the same, but should also be addressed in the future)

2016-10-31 16:17 UTC, jeabakker commented on engine/lib/views.php
> +
?????

2016-10-31 16:17 UTC, jeabakker commented on views/default/admin.css.php
what about widget header colors? If the front-end css is used on the backend?

2016-10-31 16:19 UTC, jeabakker commented on views/default/admin.css.php
@Elgg/core thoughts

2016-10-31 18:32 UTC, hypeJunction commented on views/default/admin.css.php
I don't mind

2016-10-31 18:35 UTC, hypeJunction approved these changes

2016-10-31 19:13 UTC, merged