feat(js): lightbox href calls no run through elgg/Ajax
Elgg/Elgg pull request #10545
Opened 2016-11-01 12:35 UTC by jdalsem

fixes #10078

2016-11-01 12:36 UTC, jdalsem commented
can't use onLoad callbacks or cbox_load event as they can not be asynchronous

2016-11-01 15:15 UTC, mrclay requested changes

2016-11-01 15:15 UTC, mrclay commented on views/default/elgg/lightbox.js
> +						var href = opts.href
Needs semicolon

2016-11-01 15:15 UTC, mrclay commented on views/default/elgg/lightbox.js
> +						lightbox.open(opts);
Just return after this?

2016-11-01 15:15 UTC, mrclay commented on views/default/elgg/lightbox.js
> +								opts.html = undefined;
Are you certain this is necessary?

2016-11-01 15:19 UTC, mrclay commented
I guess a downside here is unexpected colorbox events.

2016-11-01 15:36 UTC, jdalsem commented on views/default/elgg/lightbox.js
> +								opts.html = undefined;
100%... if you reopen the lightbox... the content would otherwise still be there (and you would see no loader)

2016-11-01 15:37 UTC, jdalsem commented
> I guess a downside here is unexpected colorbox events.

like? because of the extra 'open'?

2016-11-01 16:15 UTC, jdalsem commented on views/default/elgg/lightbox.js
> +						lightbox.open(opts);
done

2016-11-01 16:42 UTC, hypeJunction commented on views/default/elgg/lightbox.js
> +							opts.html = undefined;
Let's trigger jQuery events here, similar to popup and tabs

2016-11-01 16:44 UTC, jdalsem commented on views/default/elgg/lightbox.js
> +							opts.html = undefined;
why? we have events in colorbox....

2016-11-01 16:47 UTC, hypeJunction commented on views/default/elgg/lightbox.js
> +							opts.html = undefined;
It's easier to listen to jQuery events.

2016-11-10 08:14 UTC, jdalsem commented
If we want extra 'special' jquery events we can always add those later. It is not needed for this PR, so merging this.

2016-11-10 08:14 UTC, merged