feat(core): it now is possible to ignore_access during elgg_get_entities
Elgg/Elgg pull request #10571
Opened 2016-11-08 23:49 UTC by jdalsem

fixes #10401

2016-11-09 17:31 UTC, juho-jaakkola requested changes

2016-11-09 17:31 UTC, juho-jaakkola commented on engine/classes/Elgg/Database/EntityTable.php
> +			$old_ia = elgg_set_ignore_access(true);
```php
$this->session->setIgnoreAccess(true);
```

2016-11-09 17:31 UTC, juho-jaakkola commented on engine/classes/Elgg/Database/EntityTable.php
> +			elgg_set_ignore_access($old_ia);
```php
$this->session->setIgnoreAccess($old_ia);
```

2016-11-09 17:59 UTC, hypeJunction commented
I don't think this will work either way unless all metadata is loaded with the entity. The sql query will only be built with ignored access for the entity table row. Speaking from experience

2016-11-10 08:13 UTC, jdalsem commented
Closing this. It works (for some usecases) but for others you still need the 'old' pattern of ignoring access. To prevent confusion on how it works, we better stick with one approach.

2016-11-10 08:13 UTC, closed without merging