Plugin updates
Elgg/Elgg pull request #10623
Opened 2016-11-23 12:46 UTC by jdalsem

2016-11-23 13:12 UTC, hypeJunction requested changes

2016-11-23 13:12 UTC, hypeJunction commented on mod/invitefriends/actions/invitefriends/invite.php
>  		register_error(elgg_echo('invitefriends:already_members', array(implode(', ', $already_members))));
Put in the error response.

2016-11-23 13:12 UTC, hypeJunction commented on mod/logrotate/start.php
> +	if ($delete !== 'never') {
Register the hook and terminate if never

2016-11-23 13:12 UTC, hypeJunction commented on mod/logrotate/start.php
>  	elgg_register_plugin_hook_handler('cron', $period, 'logrotate_archive_cron');
Don't query for settings. Register for all and match type against settig and terminate early.

2016-11-23 13:12 UTC, hypeJunction commented on mod/logrotate/views/default/plugins/logrotate/settings.php
> +	'value' => $plugin->delete,
scary name...

2016-11-23 13:31 UTC, jdalsem commented on mod/logrotate/views/default/plugins/logrotate/settings.php
> +	'value' => $plugin->delete,
yep... would not have been my choice either :)

2016-11-23 13:50 UTC, jdalsem commented
@hypeJunction addressed your comments

2016-11-24 07:19 UTC, hypeJunction commented on mod/invitefriends/actions/invitefriends/invite.php
>  		register_error(elgg_echo('invitefriends:already_members', array(implode(', ', $already_members))));
Ah I see. Maybe we should allow an array for error and success messages?

2016-11-24 07:39 UTC, hypeJunction submitted a review, later dismissed

2016-11-24 07:39 UTC, hypeJunction commented on mod/invitefriends/start.php
> +		elgg_register_menu_item('page', [
Kind of to go away from this pattern and use menu hooks

2016-11-24 07:39 UTC, hypeJunction commented on mod/invitefriends/start.php
> +		elgg_register_menu_item('page', [
Want*

2016-11-24 07:39 UTC, hypeJunction commented on mod/invitefriends/start.php
> +	echo elgg_view_resource('invitefriends');
Let's use invitefriends/index or something so it's easier to extend later if needed

2016-11-24 07:39 UTC, hypeJunction commented on mod/invitefriends/views/default/forms/invitefriends/invite.php
> +	'value' => elgg_get_sticky_value('invitefriends', 'emails'),
My preference is to keep the form wrapper view, prepare the vars there merging sticky values and only extract values from vars in form views

2016-11-24 07:39 UTC, hypeJunction commented on mod/invitefriends/start.php
>  		return false;
Can't see what's here on my phone. Move all logic out of page handler and move to resource view (gatekeeper or whatever that is)

2016-11-24 07:39 UTC, hypeJunction commented on mod/logrotate/start.php
> +	if ($period == 'never') {
This won't happen. Cron hook types are limited to cron periods IMO

2016-11-24 07:39 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/add.php
> +$output = elgg_list_annotations([
Hmm. Not how I intrnded to use this. I'd rather pass annotation instance and a view if needed. The response factory will export an annotation into an object.

```php
[
   'annotation' => ElggAnnotation,
   'view' => string,
   'action' => 'create',
]
```

2016-11-24 07:39 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
Send deleted message with the response?

2016-11-24 07:39 UTC, hypeJunction commented on mod/messageboard/start.php
> +		'text' => elgg_view_icon('delete'),
Meh. Use new icon and text separately and hide with css if needed

2016-11-24 07:39 UTC, hypeJunction commented on mod/messageboard/views/default/elgg/messageboard.js
> +			form.on('click', 'button[type=submit]', MB.submit);
Remove tag name or better use submit event

2016-11-24 07:39 UTC, hypeJunction commented on mod/messageboard/views/default/forms/messageboard/add.php
> +	'#type' => 'plaintext',
Switch to longtext with disabled editor?

2016-11-24 08:02 UTC, jdalsem commented on mod/invitefriends/actions/invitefriends/invite.php
>  		register_error(elgg_echo('invitefriends:already_members', array(implode(', ', $already_members))));
will do

2016-11-24 08:03 UTC, jdalsem commented on mod/invitefriends/views/default/forms/invitefriends/invite.php
> +	'value' => elgg_get_sticky_value('invitefriends', 'emails'),
well you could also prepare in the resource view... do not see the need for the wrapper view...
will move the preparation to the resource view

2016-11-24 08:05 UTC, jdalsem commented on mod/messageboard/actions/messageboard/add.php
> +$output = elgg_list_annotations([
why would this not be intended? it works very well :)

2016-11-24 08:05 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
can do...

2016-11-24 08:07 UTC, jdalsem commented on mod/messageboard/views/default/elgg/messageboard.js
> +			form.on('click', 'button[type=submit]', MB.submit);
main plan was to get this working again :) i did not want to refactor this js too much... as there should be an end to all the work :)

2016-11-24 08:07 UTC, jdalsem commented on mod/messageboard/views/default/forms/messageboard/add.php
> +	'#type' => 'plaintext',
what would be the reason? just checking... not against changing

2016-11-24 08:09 UTC, jdalsem commented on mod/invitefriends/start.php
> +	echo elgg_view_resource('invitefriends');
will do

2016-11-24 08:32 UTC, hypeJunction commented on mod/messageboard/views/default/forms/messageboard/add.php
> +	'#type' => 'plaintext',
Consistency, I suppose. No biggie. To be honest I'd rather loose messageboard entirely :)

2016-11-24 08:33 UTC, hypeJunction commented on mod/messageboard/views/default/elgg/messageboard.js
> +			form.on('click', 'button[type=submit]', MB.submit);
Well, `[type="submit"]` is safer and BC

2016-11-24 08:34 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
Not entirely sure if it will work after the delete. Maybe export to object and then pass as `deleted`?

2016-11-24 08:35 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/add.php
> +$output = elgg_list_annotations([
Plus you can't do anything with the list in JS other than inject into DOM, with an exported list you can do other stuff.

2016-11-24 08:36 UTC, hypeJunction commented on mod/invitefriends/views/default/forms/invitefriends/invite.php
> +	'value' => elgg_get_sticky_value('invitefriends', 'emails'),
Well, we did the same with lists, in the end we ended up moving list rendering into `listing/` views. I'd rather we keep resource elements separate, so it's easy to replace the form/add vars without hacking the resource view.

2016-11-24 09:09 UTC, jdalsem commented on mod/invitefriends/start.php
>  		return false;
done

2016-11-24 09:09 UTC, jdalsem commented on mod/invitefriends/start.php
> +		elgg_register_menu_item('page', [
done

2016-11-24 09:12 UTC, jdalsem commented on mod/messageboard/actions/messageboard/add.php
> +$output = elgg_list_annotations([
leaving this as is for now... as it is the same as the 'old' behaviour

2016-11-24 09:12 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
not following what you mean

2016-11-24 09:41 UTC, jdalsem commented on mod/messageboard/views/default/elgg/messageboard.js
> +			form.on('click', 'button[type=submit]', MB.submit);
done

2016-11-24 09:51 UTC, jdalsem commented on mod/invitefriends/actions/invitefriends/invite.php
>  		register_error(elgg_echo('invitefriends:already_members', array(implode(', ', $already_members))));
hmmm leaving this as is for now... don't know what we would do with the error that is passed to the Response when it is an array... you could do a follow up PR if you have an idea how to approach this

2016-11-24 09:52 UTC, jdalsem commented on mod/messageboard/views/default/forms/messageboard/add.php
> +	'#type' => 'plaintext',
leaving this as is for now... don't want to surprise people with all kinds of longtext embed features in the messageboard

2016-11-24 10:05 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
nope it can't resolve after deletion...

2016-11-24 10:09 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
so, perhaps before delete:
```php
$data = [
   'entity' => $entity->toObject(),
]
```

2016-11-24 10:16 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
Works... is this what you had in mind?
![message_board_deleted](https://cloud.githubusercontent.com/assets/861833/20594656/5c99d5da-b237-11e6-937c-fd9fa6ffbe8c.png)

2016-11-24 10:17 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
which format would make sense the most?

2016-11-24 10:26 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
I guess we are setting a convention here, eh? 
I think `entity` would be misleading. Let's use `deleted`.

2016-11-24 10:27 UTC, hypeJunction commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
We need to fix annotation export. It should include type and subtype.

2016-11-24 11:37 UTC, jdalsem commented on mod/messageboard/actions/messageboard/delete.php
> +	return elgg_ok_response('', elgg_echo('messageboard:deleted'));
added it to the delete action..  can fix the export in a separate PR...

2016-11-24 14:52 UTC, hypeJunction approved these changes

2016-11-24 15:55 UTC, merged