feat(groups): consolidate API for joining groups
Elgg/Elgg pull request #10661
Opened 2016-12-16 11:40 UTC by hypeJunction

Removes groups_join_group() and moves additional groups plugin logic
to an event handler.

BREAKING CHANGE
groups_join_group() has been removed: use ElggGroup::join() instead.

2016-12-16 12:16 UTC, jdalsem commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
do we need to tackle this inside group->join ??

2016-12-16 12:31 UTC, hypeJunction commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
This shouldn't be there to start with. I looked through the stack and there is no reason for ignored access. If handlers need it, they can add it themselves. `$group` is already loaded and access hooks don't check access.

2016-12-16 13:56 UTC, jdalsem commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
Reason is the hidden groups.... https://github.com/Elgg/Elgg/issues/1926 describes the issue... could you test if that is no longer an issue?

2016-12-16 21:06 UTC, hypeJunction commented
We need to allow passing options to `ElggGroup::join()`, e.g. to disable river item creation - would make sense when the group is initially created and the owner is added as member.

2016-12-23 10:41 UTC, jdalsem commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
i tested the scenario described in the ticket... the problem is back... so there still needs to be done something special with the entity (maybe not as part of join) in the invite action

2017-01-14 11:13 UTC, hypeJunction commented
This has been reworked, added some tests against #1926

2017-01-23 09:10 UTC, jdalsem requested changes

2017-01-23 09:10 UTC, jdalsem commented on engine/classes/ElggGroup.php
> +		if (_elgg_services()->events->hasHandler('leave', 'group')) {
why not use `triggerDeprecated`

2017-01-23 09:10 UTC, jdalsem commented on engine/classes/ElggGroup.php
> +		if (_elgg_services()->events->hasHandler('join', 'group')) {
why not use `triggerDeprecated`?

2017-01-23 09:13 UTC, jdalsem commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
other than creating a test for the scenario... what did you change to fix this?

2017-01-26 13:55 UTC, jdalsem commented
if you address my requested changes this can be merged

2017-01-26 17:13 UTC, mrclay commented
Is this switching from an event to hook just to send params? Again wondering we we don't add params to events.

2017-01-26 17:24 UTC, hypeJunction commented
Our notification system is based on events and expects a single event object. I don't think we can easily add params to events (nor should we). I think of Elgg events as a notification about an entity mutation, everything else is hooks. In this particular case, I would even remove the event/hook completely - it's a duplication of create, relationship event, and creates additional boilerplate.

2017-03-11 20:04 UTC, hypeJunction commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
The code reading the group_acl in the hook was wrapped in elgg_set_ignore_access()

2017-03-11 20:05 UTC, hypeJunction commented on mod/groups/start.php
> -	$ia = elgg_set_ignore_access(TRUE);
https://github.com/Elgg/Elgg/pull/10661/files#diff-d69a9c513b5e301164eb156de0de8db5R606

2017-03-29 17:09 UTC, closed without merging

2017-07-26 12:49 UTC, jdalsem commented
why was this closed? It was on the right track...

2017-07-26 13:06 UTC, hypeJunction commented
I deleted my fork

2017-07-31 14:03 UTC, hypeJunction commented
The branches have diverged too much. Should have been merged when it was still fresh. Not going to spend time recovering this.