feat(views): make layout header responsive
Elgg/Elgg pull request #10680
Opened 2016-12-28 11:42 UTC by hypeJunction

Replaces floats with flexbox. Improves spacing between layout
heading and menu

2016-12-28 13:33 UTC, jdalsem requested changes

2016-12-28 13:33 UTC, jdalsem commented on views/default/elements/layout.css.php
> +  border-bottom: 1px solid #EBEBEB;
use tabs instead of spaces

2016-12-28 14:20 UTC, hypeJunction commented on views/default/elements/layout.css.php
> +  border-bottom: 1px solid #EBEBEB;
hm. odd, I thought they were...

2017-01-14 12:17 UTC, hypeJunction commented
@jdalsem address the tab issue

2017-01-19 13:59 UTC, jdalsem approved these changes

2017-01-19 13:59 UTC, merged