feat(search): adds a new core search service
Elgg/Elgg pull request #10688
Opened 2017-01-05 13:52 UTC by hypeJunction

Adds a new search service that behaves similar to elgg_get_entities().

BREAKING CHANGE
Most of search plugin views have been updated or removed.
Tag search has been combined with the entity search.
Some of the search behavior may have changed, search hooks have been deprecated.

- [ ] Update docs
- [ ] Add tests

2017-01-05 13:54 UTC, hypeJunction commented
@beck24 Hope to get your input on this. This should pay ok with Solr, but if there is anything to improve, let me know.

2017-01-05 13:55 UTC, hypeJunction commented on docs/guides/upgrading.rst
> - * ``ElggSite::isPublicPage``: Logic moved to the router and should not be accessed directly
Bring back

2017-01-05 13:55 UTC, hypeJunction commented on docs/guides/upgrading.rst
>   * ``search_get_where_sql`` no longer supports the argument ``use_fulltext``
Update a list of removed functions

2017-01-05 14:12 UTC, hypeJunction commented
Re: tag search. I never understood the logic behind separating tag search. Not sure why profile fields are search by default for users, but not tags. Things are too corky around tags.

2017-01-05 14:55 UTC, hypeJunction commented
The problem is what we consider tags. This global tag name registration is bad. Something that's a tag on an object might contain sensitive metadata on user entity. I'd rather we get rid of tag name registration all together, and made everyone use 'search:fields' hooks.

2017-01-05 15:03 UTC, jdalsem commented
> This global tag name registration is bad

agree... removal of this feature is fine by me... it currently is only used in search AFAICT

2017-01-05 15:33 UTC, hypeJunction commented
> **Search in:**
>  - everywhere (whatever defaults)
>  - tags
> - titel
> - title + description

This is really easy now with ``elgg_search()``. I say we agree on the default and let plugins devs extend as they please.

``elgg_search([
   'type' => 'user',
   'fields' => [
      'name', 'username', 'interests',
   ],
]);
``

2017-01-05 15:36 UTC, jdalsem commented
user/group should search all profile fields of the 'tag' type

2017-01-05 15:39 UTC, hypeJunction commented
I don't really care what we do with the search plugin and what we configure as default. I just need to create an API that's easy to use and customize. The way I see it, we search everywhere, devs can then customize search fields using hooks.

2017-01-05 15:40 UTC, jdalsem commented
agreed

2017-01-05 16:16 UTC, jdalsem requested changes
various files have been touched for no reason... would make it easier to read if you could fix that... 

Need to test a bit more to see if my personal use cases can be fullfilled with this PR... looking good so far

2017-01-05 16:16 UTC, jdalsem commented on engine/classes/Elgg/Di/ServiceProvider.php
> +		$this->setFactory('search', function(ServiceProvider $c) {
name it searchService...

2017-01-05 16:16 UTC, jdalsem commented on engine/classes/Elgg/Router.php
> -
file touched for no reason

2017-01-05 16:16 UTC, jdalsem commented on engine/classes/Elgg/Search/SearchService.php
> +			$clauses['wheres'][] = "(($attributes_where) OR ((({$md_clauses['wheres'][0]}) AND $metadata_where)))";
probably need md access

2017-01-05 16:16 UTC, jdalsem commented on engine/classes/Elgg/Search/SearchService.php
> +				// avoid notices
shouldn't this be fixed in `_get_metastrings_options`?

2017-01-05 16:16 UTC, jdalsem commented on engine/classes/ElggSite.php
> -
touched for no reason

2017-01-05 16:16 UTC, jdalsem commented on engine/lib/elgglib.php
> -
touched for no reason

2017-01-05 16:16 UTC, jdalsem commented on engine/tests/phpunit/Elgg/RouterTest.php
> -
touched for no reason

2017-01-05 16:16 UTC, jdalsem commented on mod/discussions/start.php
> +	elgg_register_plugin_hook_handler('search_types', 'get_queries', 'discussion_filter_search_types');
hook name and type are a bit confusing...

Why not 'search', 'get_types'???

2017-01-05 16:16 UTC, jdalsem commented on mod/search/views/default/forms/search.php
> +	'container_guid' => get_input('container_guid'),
should we actively display which filters apply? so we could unset with a click?

2017-01-05 16:16 UTC, jdalsem commented on views/default/page/elements/sidebar.php
> +echo elgg_view('search/search_box');
don't know if this will eventually be the best place... but probably better to work with than extending views

2017-01-05 16:29 UTC, hypeJunction commented on engine/classes/Elgg/Router.php
> -
Yeah, I did a soft reset against master that wasn't in sync. I will fix that later.

2017-01-05 16:29 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +				// avoid notices
What is `this` and what needs to be `fixed`?

2017-01-05 16:30 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +			$clauses['wheres'][] = "(($attributes_where) OR ((({$md_clauses['wheres'][0]}) AND $metadata_where)))";
It's in metadata where clauses.

2017-01-05 16:31 UTC, hypeJunction commented on mod/discussions/start.php
> +	elgg_register_plugin_hook_handler('search_types', 'get_queries', 'discussion_filter_search_types');
Ask whoever came up with that first. It's an old hook that was in the search plugin forever.

2017-01-05 16:31 UTC, hypeJunction commented on mod/search/views/default/forms/search.php
> +	'container_guid' => get_input('container_guid'),
Extended search plugin can do that I suppose. But can be done here as well...

2017-01-05 18:39 UTC, jdalsem commented on engine/classes/Elgg/Search/SearchService.php
> +				// avoid notices
the fact that without the `null` values you will get notices... this feels silly

2017-01-05 18:41 UTC, jdalsem commented on mod/discussions/start.php
> +	elgg_register_plugin_hook_handler('search_types', 'get_queries', 'discussion_filter_search_types');
can't we change this while we are breaking? or trigger the old hook in a new hook?

2017-01-05 18:46 UTC, jdalsem commented on mod/search/views/default/forms/search.php
> +	'container_guid' => get_input('container_guid'),
maybe, but as we allow filtering based on container, why not at least display that we use that filter...

on a side note... why do we have support for owner_guid ... nowhere in core you have the ability to activate that filter

2017-01-05 18:51 UTC, jdalsem commented on engine/classes/Elgg/Search/SearchService.php
> +			$clauses['wheres'][] = "(($attributes_where) OR ((({$md_clauses['wheres'][0]}) AND $metadata_where)))";
is it? can't see how it makes it to this place...

2017-01-05 20:43 UTC, hypeJunction commented on engine/classes/Elgg/Di/ServiceProvider.php
> +		$this->setFactory('search', function(ServiceProvider $c) {
I renamed to search. They are all services. Tautology, IMO

2017-01-05 20:44 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +				// avoid notices
Need to dig deeper to see if needed. This was copied from search plugin

2017-01-05 20:52 UTC, hypeJunction commented on mod/discussions/start.php
> +	elgg_register_plugin_hook_handler('search_types', 'get_queries', 'discussion_filter_search_types');
Not sure. Do other have an opinion?

2017-01-05 20:52 UTC, hypeJunction commented on mod/search/views/default/forms/search.php
> +	'container_guid' => get_input('container_guid'),
Not sure. I dropped friends because I didn't see it used anywhere. Can drop owner

2017-01-05 21:23 UTC, hypeJunction commented
> Need to test a bit more to see if my personal use cases can be fullfilled with this PR... looking good so far

Let me know. This covers my use cases, but I am sure there are more.

2017-01-14 13:03 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +				// avoid notices
Metadata is no longer access controlled

2017-01-14 13:04 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +			$clauses['wheres'][] = "(($attributes_where) OR ((({$md_clauses['wheres'][0]}) AND $metadata_where)))";
metadata is no longer access controlled

2017-01-14 16:47 UTC, hypeJunction commented
Livesearch has been rewritten

2017-01-14 16:50 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +					$clauses['wheres'][] = "{$table}.banned = 'no'";
`secondary.banned`

2017-01-14 19:11 UTC, hypeJunction commented on views/json/resources/livesearch/friends.php
> +	'wheres' => [
Move this to users with a friends_only check. This view just sets friends only to true to renders users

2017-01-14 19:11 UTC, hypeJunction commented on views/default/input/userpicker.php
> +		echo elgg_view('input/checkbox', [
Should we just get rid of this? I don't see how this makes better UX

2017-01-14 19:11 UTC, hypeJunction commented on views/default/input/autocomplete.php
> +	require(['elgg/autocomplete'], function (autoc) {
We could just bind autocomplete initiation to focus event on the field

2017-01-16 13:17 UTC, hypeJunction commented
@Elgg/core Please provide your feedback. I need to wrap this up and a couple more things before February starts, then I will have no more availability for the 3 following months.

2017-01-16 13:26 UTC, hypeJunction commented on engine/classes/Elgg/Search/SearchService.php
> +				'order_by_metadata' => $order_by_metadata,
Double check what clauses this returns

2017-01-16 13:41 UTC, hypeJunction commented
Re: Solr and other indexing engines. They just tap into `search:options`, sniff out `$options['count']` and return either the count or an array of guids and strip out all other options.

2017-03-07 18:32 UTC, hypeJunction commented on views/default/page/elements/sidebar.php
> +echo elgg_view('search/search_box');
I am intending to move the search into the topbar.

2017-03-07 18:33 UTC, hypeJunction commented
I have started adding some tests. @mrclay, do you mind taking a look at the tests to see if the strategy is viable enough.

2017-03-07 18:35 UTC, hypeJunction commented on engine/tests/ElggCoreSearchTest.php
> +			'query' => ' argentina ',
Not sure what tokenization without a partial match should do... It kinds of doesn't make sense to tokenize something if you are not allowing partial matches.

2017-03-07 19:08 UTC, mrclay commented on views/default/input/userpicker.php
> +		UserPicker.setup('.elgg-user-picker[data-name=<?= json_encode($name) ?>]');
This is fine. In an ideal world we'd use CSS.escape or its [polyfill](https://github.com/mathiasbynens/CSS.escape/blob/master/css.escape.js).

2017-03-07 19:11 UTC, mrclay commented
- [ ] workaround new search deprecations

2017-03-07 19:16 UTC, mrclay commented
In case you're unaware `container_guid` in URL seems to be ignored.

2017-03-29 17:08 UTC, closed without merging