feature(likes): Delete permissions of likes for like owners, liked entity owners and group owners
Elgg/Elgg pull request #10704
Opened 2017-01-15 14:05 UTC by iionly

2017-01-16 08:08 UTC, hypeJunction requested changes

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +	if ($annotation->owner_guid == $user->guid) {
Is this necessary? I think it's the default

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +	if ($liked_on->owner_guid == $user->guid) {
Is this necessary? I think it's the default.

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +	if (elgg_instanceof($container, 'group') && $container->owner_guid == $user->guid) {
`$container->canEdit()`

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +	} else if ((elgg_instanceof($liked_on, 'object', 'comment') || elgg_instanceof($liked_on, 'object', 'discussion_reply')) && elgg_instanceof($container, 'object')) {
`instanceof ElggComment`

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +		if (elgg_instanceof($container, 'group') && $container->owner_guid == $user->guid) {
`$container->canEdit()`

2017-01-16 08:08 UTC, hypeJunction commented on mod/likes/start.php
> +	return false;
I'd rather not. We should work from reverse.

2017-04-02 13:56 UTC, iionly commented
Closing. Will provide this functionality with a plugin instead.

2017-04-02 13:56 UTC, closed without merging