fix(actions): remove php execution timeout for all actions #7204
Elgg/Elgg pull request #10745
Opened 2017-01-31 20:17 UTC by Phanoix

This removes the php execution timeout for all registered actions to fix #7204.

2017-01-31 21:47 UTC, hypeJunction commented
I'd prefer a reasonably high limit rather than no limit. If you are doing something that runs for 9 million seconds you should probably not be doing that in an action. There are bound to be memory issues as well unless the code doesn't leak any memory for the duration of the action.

2017-01-31 21:57 UTC, Phanoix commented
That's a good point, maybe the limit should be added as a setting?

2017-01-31 22:24 UTC, Phanoix commented
so something like:
``` php
if ( ini_get('max_execution_time') < 120 );
    set_time_limit(120);
```

2017-01-31 22:37 UTC, hypeJunction commented
Playing with ini values is asking for trouble, IMO. I bet there are compilations that use different values/vars, perhaps xdebug chimes in as well.
Let's maybe add an Elgg $CONFIG parameter with no default, let site admins configure if they experience time outs?

2017-02-01 00:55 UTC, Phanoix commented
Updated, it will now check $CONFIG->action_time_limit and set the timeout to that if it is set.

2017-02-01 07:27 UTC, jdalsem commented on engine/classes/Elgg/ActionsService.php
> +		if (isset($CONFIG->action_time_limit)) {
can we use elgg_get_config?

2017-02-01 07:28 UTC, jdalsem commented
as this is actually a feature and not a bugfix, this should go against the master branch... also update the commit message to be a feature...

2017-02-01 07:47 UTC, hypeJunction requested changes
Could you also add it to setting example with a suggested value of 120? and some comments. That way it will get copied over on new installations

2017-02-01 12:36 UTC, hypeJunction commented
@Phanoix In my comment, I was referring to https://github.com/Elgg/Elgg/blob/master/elgg-config/settings.example.php

2017-02-01 13:30 UTC, jeabakker commented on engine/classes/Elgg/ActionsService.php
> +		if (isset($CONFIG->action_time_limit)) {
or better yet `$this->config->get();`

2017-02-01 20:04 UTC, Phanoix commented
It's now getting the setting from $this->config->get('action_time_limit'); and I added a section for it in the example settings.

2017-02-02 08:07 UTC, jdalsem commented
We are almost there... the PR should be on master instead of 2.3 as 2.3 only accepts bugfixes and this is a feature. Otherwise this LGTM

Oh and can you add something to the docs? in docs/info/config.php?

2017-02-02 14:36 UTC, Phanoix commented
Changed to merge into master, I'll replicate the changes off the master branch.

2017-04-07 16:06 UTC, merged

2017-04-07 16:07 UTC, mrclay commented
@Phanoix thanks! Sorry this sat so long.