chore(views): River group string moved to summary view - #7872
Elgg/Elgg pull request #10761
Opened 2017-02-10 20:19 UTC by piet0024

Moving the group summary string from river/elements/body to river/elements/summary. Closes #7872

2017-02-10 22:48 UTC, hypeJunction approved these changes

2017-02-13 08:21 UTC, jdalsem requested changes

2017-02-13 08:21 UTC, jdalsem commented on views/default/river/elements/summary.php
> +$summary .= ' ' . $group_string;
this will result in trailing spaces if group string is empty

2017-02-13 08:21 UTC, jdalsem commented on views/default/river/elements/summary.php
> +    $summary .= ' ' . $group_string;
huh... this will cause issues as you probably append group_string twice

2017-02-13 08:21 UTC, jdalsem commented on views/default/river/elements/body.php
> +<div class="elgg-river-summary">$summary <span class="elgg-river-timestamp">$timestamp</span></div>
maybe remove the space after $summary

2017-03-09 18:53 UTC, mrclay commented on views/default/river/elements/summary.php
> +$summary .= ' ' . $group_string;
Just need `trim(' ' . $group_string)`

2017-03-09 18:54 UTC, mrclay commented on views/default/river/elements/summary.php
> +    $summary .= ' ' . $group_string;
I think this is right, just needs trim().

2017-03-09 18:55 UTC, mrclay commented
@piet0024 could you amend this so we can merge it?

2017-04-06 12:02 UTC, mrclay commented
Replaced by #10872

2017-04-06 12:02 UTC, closed without merging