Merge 2.3 into master
Elgg/Elgg pull request #10833
Opened 2017-03-18 22:07 UTC by mrclay

2017-03-18 22:22 UTC, mrclay commented
Some fatal error in simpletests.

2017-03-20 07:22 UTC, jdalsem requested changes

2017-03-20 07:22 UTC, jdalsem commented on engine/classes/ElggEntity.php
> +			foreach (['owner_guid', 'container_guid', 'site_guid'] as $db_column) {
remove site_guid

2017-03-20 07:22 UTC, jdalsem commented on engine/classes/ElggEntity.php
> +			foreach (['owner_guid', 'container_guid', 'site_guid'] as $db_column) {
remove site_guid

2017-03-20 07:22 UTC, jdalsem commented
maybe my comments solve the simplecache fails

2017-03-20 14:14 UTC, jdalsem commented
New version here: #10837

2017-03-20 18:13 UTC, closed without merging