Master simplification and cleanup
Elgg/Elgg pull request #10923
Opened 2017-04-16 13:15 UTC by mrclay

**Makes boot sequence clearer**

Removes the unnecessary [boot, system] event. The installer was only using it to unregister a function that no longer exists.

Initializes context service directory after instantiation.

**Clean up**

Less reliance on global $CONFIG for non-DB functionality. See #10916.

Move action/PAM registration out of session boot.

reloadAllTranslations: don't notice if global isn't set

uservalidationbyemail_disable_new_user: simplified hook usage

2017-04-17 22:31 UTC, mrclay commented on engine/classes/Elgg/Http/Input.php
> -		$this->CONFIG = $CONFIG;
- [ ] need BREAKING notice. Don't depend on $CONFIG->input being set.

2017-04-21 11:40 UTC, jeabakker requested changes

2017-04-21 11:40 UTC, jeabakker commented on engine/lib/navigation.php
> +	$CONFIG = _elgg_services()->config->getStorageObject();
why not use `$menus = elgg_get_config('menus');` like you do in the other functions in this file?

2017-04-21 11:40 UTC, jeabakker commented on engine/lib/navigation.php
> +	$CONFIG = _elgg_services()->config->getStorageObject();
why not use `$menus = elgg_get_config('menus');` like you do in the other functions in this file?

2017-04-21 11:40 UTC, jeabakker commented on mod/uservalidationbyemail/start.php
> +		return;
don't forget to change the returnvalue of the function in the function docs

2017-04-22 02:09 UTC, mrclay commented
Decided to simplify this into multiple PRs.

2017-04-22 02:15 UTC, merged