chore(upgrade): upgrade CKEditor to latest version 4.6.2
Elgg/Elgg pull request #10967
Opened 2017-05-24 13:47 UTC by smellems

Closes #9283

2017-05-24 13:55 UTC, hypeJunction commented
It's a breaking change and would need to go into master

2017-05-24 15:31 UTC, smellems commented
What does it break?  I'm also looking at upgrading it in our 1.12..

2017-05-24 16:55 UTC, hypeJunction commented
You are bringing a feature release of CKEditor in a bugfix branch of Elgg.

2017-05-24 18:49 UTC, mrclay commented
In master branch we might as well drop all these vendor files. #10968

2017-05-24 18:50 UTC, mrclay commented
> I'm also looking at upgrading it in our 1.12

You'll need to make a separate plugin anyway.

2017-05-25 13:03 UTC, smellems commented
I changed this to update to 4.4.8 for branch 2.3.  I can make another pull request for 4.6.2, for master.

2017-05-25 13:08 UTC, mrclay requested changes

2017-05-25 13:08 UTC, mrclay commented on mod/ckeditor/views/default/elgg/ckeditor/config.js
> -		extraPlugins: 'blockimagepaste,autogrow',
Why are these removals being made? At the very least they should be mentioned in the PR description for transparency.

2017-05-25 13:14 UTC, smellems commented on mod/ckeditor/views/default/elgg/ckeditor/config.js
> -		extraPlugins: 'blockimagepaste,autogrow',
`blockimagepaste `is not a plugin in the plugin folder, same for `contextmenu`.  `liststyle `and `tabletools `were already being removed.

#9172

2017-05-26 03:02 UTC, mrclay commented on mod/ckeditor/views/default/elgg/ckeditor/config.js
> -		extraPlugins: 'blockimagepaste,autogrow',
I'm OK with this, but @Elgg/core should probably determine if the functionality these plugins were providing is still needed.

2017-05-26 03:02 UTC, mrclay approved these changes

2017-05-26 09:10 UTC, iionly commented
May I suggest to include the "full package" of the CKEditor plus at least the plugins already in use by Elgg additionally (e.g. autogrow isn't part of the "full package") even if not all of these plugins are being used in the default Elgg ckeditor config.

I think it would be easier that way for anyone who wants to customize their editor config as it would only be necessary to override the views and not to create a complete plugin that contains the plugin missing in the bundled ckeditor plugin. With https://github.com/hypeJunction/Elgg-ckeditor_addons there's even a plugin already available that allows to define the editor config via the admin backend and such a plugin would fail to work if some of the required plugins wouldn't be included while the corresponding features could still be selected.

2017-05-26 10:25 UTC, hypeJunction commented
This should go into master in any case, I don't think there is place for these changes in a bugfix release. And while at it, as @mrclay suggested, vendor libraries should be pulled via bower or something. Perhaps it would make sense to extract the plugin into its own repo and pull via composer.

2017-05-26 16:33 UTC, smellems commented
This is the "full package" with the `autogrow` plugin addded.

I can also make the change in master.  Not sure how you would like it.

2017-12-06 12:48 UTC, jdalsem commented
Replaced by #11453

2017-12-06 12:48 UTC, closed without merging