Removed headers and messageID
Elgg/Elgg pull request #10991
Opened 2017-07-18 14:24 UTC by rconjour

Removed php based messageID, this gives in outlook.com errors and removed headers. So elgg emails wouldn't be marked as spam anymore.

2017-07-18 14:48 UTC, jeabakker requested changes
Why do you believe this will help in spam prevention? Any source article/knowledge base article that supports the statement?

2017-07-18 14:48 UTC, jeabakker commented on engine/lib/notification.php
> -	foreach ($result['headers'] as $headerName => $headerValue) {
this should not be removed, as plugin hooks can return header lines which need to be set

2017-07-18 14:53 UTC, rconjour commented
If you check at https://www.mail-tester.com you can see that spam assassin fails on the Message ID. And by trail and error we've found out that outlook.com doesn't accept the emails untill we removed the headers and left it to postfix or any other mail handler (f.e dovecot).

The current header didn't approve to the RFC-2822 protocol.

2017-07-18 15:02 UTC, jeabakker commented
do you have any examples of failed `message-id` headers so we can maybe improve the headers

2017-07-18 15:12 UTC, rconjour commented
The email has this messageID:
Message-ID: =?UTF-8?Q?</.default.1500386798.1914@domainremovedbyme.nl>?=

After the changes it looks like this:
Message-ID: <20170718145925.AB2F460138D6@domainremovedbyme.nl>

2017-07-18 15:45 UTC, jeabakker commented
i think i found the problem, as you can see the failed message-id is UTF-8 encoded, the other isn't.

i'm trying to find out why this is happening

2017-07-18 15:55 UTC, cleverthings commented
Great job rconjour & jeabakker for catching that one and for your persistence in fixing it - you are both awesome!

2017-07-18 20:16 UTC, hypeJunction commented
I've had issues with Outlook due to wrong content-type headers but not message id. I don't really see why message id would qualify something as spam, though incorrect UTF encoding might be the culprit.

2017-07-18 20:17 UTC, hypeJunction commented
I'd dig through Zend Mail code to see when it forces UTF encoding. Perhaps the ID contains multi-byte characters, what's the actual domain you use?

2017-07-25 11:43 UTC, jeabakker commented
I found the issue and will create a new PR to fix it, closing this PR

2017-07-25 11:43 UTC, closed without merging