Improvements to pages plugin
Elgg/Elgg pull request #11080
Opened 2017-08-02 06:52 UTC by hypeJunction

2017-08-02 06:57 UTC, jdalsem commented on composer.json
> +        "bower-asset/jquery-treeview": "^1.4"
no like... i know why you did this, but still i do not like it... can accept for now, but in an ideal world this should stay with the plugin composer..

2017-08-02 06:57 UTC, jdalsem approved these changes

2017-08-02 07:08 UTC, hypeJunction commented on composer.json
> +        "bower-asset/jquery-treeview": "^1.4"
Yes, ideally, pages plugin would live in its own repo

2017-08-02 07:11 UTC, hypeJunction commented on mod/pages/start.php
> +		'categries' => 'categories',
typo

2017-08-02 07:12 UTC, hypeJunction commented on mod/pages/views/default/resources/pages/view.php
> +$content .= elgg_view_comments($page);
Should go into `responses`

2017-08-02 07:39 UTC, jeabakker requested changes

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/lib/pages.php
>  	if ($pages) {
is a quick return possible here?

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/pages/input/parent.php
maybe also add a deprecation notice so devs actually change the use of this view

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/resources/pages/edit.php
> +$body = elgg_view_layout('content', array(
shouldn't this be a short array eg `[]`

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/resources/pages/view.php
> +$content = elgg_view_entity($page, array('full_view' => true));
short array notation

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/resources/pages/view.php
> +	elgg_register_menu_item('title', array(
short array notation

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/resources/pages/view.php
> +$body = elgg_view_layout('content', array(
short array notation

2017-08-02 07:39 UTC, jeabakker commented on mod/pages/views/default/input/pages/parent.php
> +$defaults = array(
short array notation

2017-08-02 12:41 UTC, mrclay commented on composer.json
> +        "bower-asset/jquery-treeview": "^1.4"
Can this be brought in via package.json? (and ideally all the others)

2017-08-02 12:42 UTC, mrclay commented on composer.json
> +        "bower-asset/jquery-treeview": "^1.4"
(...but I'm OK with this here)

2017-08-03 08:09 UTC, jeabakker approved these changes

2017-08-03 08:11 UTC, jdalsem commented on mod/pages/views/default/pages/input/parent.php
also deprecated is typed incorrectly

2017-08-03 08:11 UTC, hypeJunction commented
Thinking out loud: 
I think we should just loose the treeview and use our menu API. However, looking at the menu API, it feels that the whole `child_menu` approach isn't all that great. I propose we loose it, and instead add menu templates: `tree`, `navbar`

2017-08-03 08:14 UTC, jdalsem approved these changes

2017-08-03 08:14 UTC, jdalsem commented on mod/pages/views/default/pages/input/parent.php
by the way... why not just remove the view? document in upgrade and it is gone

2017-08-03 08:14 UTC, jdalsem commented on mod/pages/views/default/resources/pages/edit.php
> +elgg_set_page_owner_guid($container->guid);
doesn't this need to happen in the page handler?

2017-08-03 08:14 UTC, jdalsem commented on mod/pages/views/default/resources/pages/view.php
> +elgg_set_page_owner_guid($container->guid);
doesn't this need to happen in the page handler?

2017-08-03 08:15 UTC, jdalsem commented
> I think we should just loose the treeview and use our menu API.

also was thinking something like that... but let us finish this PR first... can remove more easier after that.... there is also a benefit to the jstree view functionality like drag/drop reordering of pages and all kinds of events

2017-08-03 08:18 UTC, hypeJunction commented on mod/pages/views/default/resources/pages/edit.php
> +elgg_set_page_owner_guid($container->guid);
Why? As far as I am concerned nothing should be happening in the page handler - they should be gone altogether.

2017-08-03 08:22 UTC, jdalsem commented on mod/pages/views/default/resources/pages/edit.php
> +elgg_set_page_owner_guid($container->guid);
can discuss this somewhere else

2017-08-03 14:09 UTC, jdalsem commented
if you just remove the deprecated view this can be merged

2017-08-03 14:31 UTC, hypeJunction commented
It's not bothering me, and I have spent way too much time on this as it is

2017-08-03 14:33 UTC, merged

2017-08-03 14:33 UTC, jdalsem commented
will remove it in a following PR