feat(blogs): more consitency in blog data during save operations
Elgg/Elgg pull request #11081
Opened 2017-08-02 07:07 UTC by hypeJunction

Blog attributes and metadata are now consistently updated when blog is saved
irrespective of whether the operation takes part in an action or outside of it.
Auto save action now uses new Ajax API.

BREAKING CHANGE
Response values of the blog/auto_save_revision action have been changed to use
new response API, instead of custom JSON objects.
Status changes to the blog entities that take place outside of the blog/save
action will now be reflected in the river.
ElggBlog class methods have been updated, so overriding classes may need to
reflect these changes

2017-08-02 07:54 UTC, jeabakker requested changes

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
why isn't this just `get_input`?

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/actions/blog/auto_save_revision.php
> +	$blog->subtype = 'blog';
isn't this handled in the constructor/initializeAttibutes of `ElggBlog`?

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/actions/blog/save.php
> +$title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
same here, why isn't this just `get_input()`?

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/actions/blog/save.php
> +	return elgg_error_response();
forgot to return the error text?

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/lib/blog.php
> +function blog_prepare_form_vars($post = NULL, $revision = NULL) {
why start shouting?

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/start.php
> +		$timestamplow = mktime(0, 0, 0, substr($date,4,2) , 1, substr($date, 0, 4));
spaces are free

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/start.php
> +				elgg_create_river_item(array(
short array  notation

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/start.php
> +				_elgg_delete_river(array(
short array notation

2017-08-02 07:54 UTC, jeabakker commented on mod/blog/views/default/forms/blog/save.php
> +		],
oops

2017-08-02 07:59 UTC, hypeJunction commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
I don't know. Been like that forever

2017-08-02 07:59 UTC, hypeJunction commented on mod/blog/lib/blog.php
> +function blog_prepare_form_vars($post = NULL, $revision = NULL) {
merge conflicts

2017-08-02 08:02 UTC, jeabakker commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
maybe improve it ;)

2017-08-02 08:05 UTC, hypeJunction commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
I think the idea is to not strip tags but to encode them, e.g. you can have a blog titled ``How to use <a> tags``

2017-08-02 08:08 UTC, jeabakker commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
you're probably right, it's just ugly

2017-08-02 12:33 UTC, mrclay commented on mod/blog/actions/blog/auto_save_revision.php
>  $title = htmlspecialchars(get_input('title', '', false), ENT_QUOTES, 'UTF-8');
Create `elgg_get_title_input()`. Goal is getting HTML-escaped (not filtered) text.

2017-08-03 15:22 UTC, jdalsem commented
Fixes #10838??

2017-10-25 12:07 UTC, closed without merging