chore(sites): sites_entity subtable attributes are moved to metadata
Elgg/Elgg pull request #11251
Opened 2017-10-06 11:56 UTC by jdalsem

Ref #2675

BREAKING CHANGE:
The sites_entity table no longer exists. Update your queries if needed.

2017-10-06 12:35 UTC, jdalsem commented
Removed some obsolete test files for ElggSite base attribute checks as they are the same as ElggEntity

2017-10-09 08:09 UTC, jeabakker requested changes

2017-10-09 08:09 UTC, jeabakker commented on docs/admin/duplicate-installation.rst
> +   $CONFIG->wwwroot = 'http://your.website.com'
add trailing `/`

2017-10-09 08:09 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +				$params[":$attr"] = ($attr === 'url') ? '' : (string) $this->attributes[$attr];
is this `if` still needed as `url` is no longer an attribute

2017-10-09 08:09 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +				$params[":$attr"] = ($attr === 'url') ? '' : (string) $this->attributes[$attr];
is this `if` still needed as `url` is no longer an attribute

2017-10-09 08:09 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +// 			return ['name', 'description', 'url'];
don't leave unused code behind

2017-10-09 08:09 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +// 					'url' => null,
don't leave unused code behind

2017-10-09 08:18 UTC, jdalsem commented
addressed all comments

2017-10-09 08:18 UTC, jeabakker approved these changes

2017-10-09 08:28 UTC, merged