chore(tests): adds view stack and rendering tests
Elgg/Elgg pull request #11311
Opened 2017-10-21 15:54 UTC by hypeJunction

Tests all core and plugin views for exestence and syntax errors.

Adds base test cases for testing view output

2017-10-21 18:58 UTC, hypeJunction commented
Could someone restart the build? It passed on Scrutinizer, so it was some freak failure

2017-10-24 11:04 UTC, jeabakker requested changes

2017-10-24 11:04 UTC, jeabakker commented on engine/tests/classes/Elgg/Plugins/ViewStackTest.php
> +		$this->assertTrue(is_readable($path));
maybe also test for `is_file`

2017-10-24 11:04 UTC, jeabakker commented on engine/tests/phpunit/unit/Elgg/Views/ViewStackTest.php
> +		$this->assertTrue(is_readable($path));
maybe also check `is_file`

2017-10-25 12:06 UTC, closed without merging