WIP Create friends ACL and get rid of ACCESS_FRIENDS
Elgg/Elgg pull request #11387
Opened 2017-11-10 16:09 UTC by jdalsem

Fixes #3391, #5038
Refs #8073, #3872

2017-11-10 16:34 UTC, jeabakker requested changes

2017-11-10 16:34 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +		if (!is_string($subtype)) {
`|| $subtype === ''`

2017-11-10 16:34 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +			throw new \InvalidParameterException('ACCESS_DEFAULT is not a valid access level. See its documentation in elgglib.php');
not `elgglib.php` but in `constants.php` ....

2017-11-10 16:34 UTC, jeabakker commented on engine/lib/access.php
> + */
`@since` and `@internal`

2017-11-10 16:34 UTC, jeabakker commented on engine/lib/access.php
> +	$events->registerHandler('create', 'user', 'access_friends_acl_create');
check if `create:after` is available

2017-11-30 14:10 UTC, jdalsem commented on engine/lib/access.php
> +	$events->registerHandler('create', 'user', 'access_friends_acl_create');
not available

2017-12-12 09:18 UTC, jdalsem commented
grr... going to redo this

2017-12-12 09:18 UTC, closed without merging