fix(i18n): fallback to site language before English
Elgg/Elgg pull request #11425
Opened 2017-11-28 09:48 UTC by jeabakker

fixes #4389

2017-11-28 09:57 UTC, jdalsem approved these changes

2017-11-28 13:24 UTC, mrclay commented
I think there's a doc somewhere that needs updating.

2017-11-28 13:27 UTC, mrclay requested changes
- [x] Update https://github.com/Elgg/Elgg/blame/master/docs/guides/i18n.rst#L8
- [x] Make sure elgg.echo has new behavior or its differences are documented.

2017-11-28 16:09 UTC, jeabakker commented
took care of documentation and JS language fallback

2017-11-30 01:42 UTC, mrclay approved these changes

2017-11-30 19:30 UTC, merged