WIP: feat(users): added generic unvalidated users page/actions
Elgg/Elgg pull request #11475
Opened 2017-12-08 16:12 UTC by jeabakker

BREAKING CHANGE: The unvalidated users page and some actions have been
moved to core and are no longer present in the uservalidationbyemail
plugin.

fixes #4561
fixes #4365

ToDo
- [ ] docs
- [ ] improved flow of validating user

2017-12-21 13:08 UTC, jeabakker commented
going to do the new method of user validation in an other PR, as that requires a bit more work and this will help non the less.

also rebased

2017-12-21 13:21 UTC, jdalsem requested changes

2017-12-21 13:30 UTC, jeabakker commented on actions/admin/user/validate.php
> +<?php
a bit more feedback

2018-01-03 15:57 UTC, jdalsem approved these changes

2018-01-03 15:57 UTC, jdalsem commented
rebase and this is ready to merge

2018-01-09 10:28 UTC, jeabakker commented
rebased

2018-01-09 14:50 UTC, merged