feat(access): the friends access is now an access collection
Elgg/Elgg pull request #11495
Opened 2017-12-12 12:22 UTC by jdalsem

Fixes #3391, #5038
Refs #8073, #3872

2017-12-12 12:22 UTC, jdalsem commented
will finish it this time...

2017-12-12 12:45 UTC, jdalsem commented on views/default/admin/upgrades.php
> +	'private_setting_value' => 0,
need to revert this

2017-12-14 11:30 UTC, jdalsem commented
Manually tested an upgrade from 2.3 to master with some entities and annotations with friends access, they seem to be migrated correctly. Tests are passing so maybe someone else can have a look at the PR

2017-12-19 09:13 UTC, jeabakker requested changes

2017-12-19 09:13 UTC, jeabakker commented on engine/classes/Elgg/Upgrades/MigrateFriendsACL.php
> +				"e.guid NOT IN (
use QueryBuilder for `wheres`

2017-12-19 09:13 UTC, jeabakker commented on engine/classes/Elgg/Upgrades/MigrateFriendsACL.php
> +				"e.guid NOT IN (
use QueryBuilder

2017-12-19 14:25 UTC, jdalsem commented
Replaced by #11506

2017-12-19 14:25 UTC, closed without merging