fix(access): flag to check user edit access
Elgg/Elgg pull request #12617
Opened 2019-05-17 12:20 UTC by rohit1290

https://github.com/Elgg/Elgg/pull/12467

creating the pull request again ref https://github.com/Elgg/Elgg/pull/12467

2019-05-17 12:34 UTC, jdalsem commented
change your commit message to `feat(gatekeeper):` as it is a feature related to gatekeeper logic

also can you change the PR to target Elgg 3.1 (i believe you can change it at the top of this PR in github)

Will examine this later

2019-05-17 12:37 UTC, jdalsem commented
we also would like to see variable split by underscores and not with camelcases so not `$canEditCheck` but `$can_edit_check`... maybe also reword this into `$validate_can_edit`

the camelCase notation is used in functions... underscores for variables

2019-05-17 13:55 UTC, jdalsem commented
the lint check fails on that same strang issue again... is your branch correctly rebased to the latest 3.0?

2019-05-17 14:41 UTC, rohit1290 commented
@jdalsem 
> can you change the PR to target Elgg 3.1

There is no 3.1 branch available in the repo

![image](https://user-images.githubusercontent.com/2772844/57935622-d6e6c980-78df-11e9-81be-4f59ba379f95.png)

2019-05-17 14:56 UTC, jdalsem commented
3.x is the next minor, so that will become the 3.1 release, so use 3.x for now

2019-06-11 09:37 UTC, rohit1290 commented
@jdalsem 
I have updated all the changes that you asked for. Do let me know if any additional changes is required for this PR.

2019-07-10 14:23 UTC, jeabakker requested changes
I believe last change request before we can merge this

2019-07-10 14:23 UTC, jeabakker commented on engine/classes/Elgg/Gatekeeper.php
> +			$user_guid = isset($user) ? (int) $user->guid : _elgg_services()->session->getLoggedInUserGuid();
replace `_elgg_services()->session->getLoggedInUserGuid()` with `$this->session->getLoggedInUserGuid()` please

2019-07-10 14:46 UTC, jdalsem requested changes

2019-07-10 14:46 UTC, jdalsem commented on mod/blog/views/default/resources/blog/edit.php
>  if (!$blog->canEdit()) {
i believe this can be removed now we have the check in the gatekeeper

2019-07-10 14:46 UTC, jdalsem commented on mod/bookmarks/views/default/resources/bookmarks/edit.php
i believe the canEdit check can be removed now we have the check in the gatekeeper

2019-07-10 14:46 UTC, jdalsem commented on mod/discussions/views/default/resources/discussion/edit.php
i believe the canEdit check can be removed now we have the check in the gatekeeper

2019-07-10 14:46 UTC, jdalsem commented on mod/pages/views/default/resources/pages/edit.php
>  if (!$page->canEdit()) {
i believe the canEdit check can be removed now we have the check in the gatekeeper

2019-07-10 17:01 UTC, rohit1290 commented
@jeabakker @jdalsem - All the changes done. It's ready to merge.

2019-07-11 07:01 UTC, merged

2019-07-11 07:03 UTC, jdalsem commented
Thanks! I created a followup ticket to add a test for this new feature #12710 12710