chore(core): replaced some old style queries
Elgg/Elgg pull request #12829
Opened 2019-09-16 14:53 UTC by jdalsem

fixes #12593

2019-09-16 15:10 UTC, jeabakker requested changes

2019-09-16 15:10 UTC, jeabakker commented on engine/classes/Elgg/BootService.php
> +// 		}
left over debugging

2019-09-16 15:12 UTC, jeabakker approved these changes

2019-09-17 08:23 UTC, jdalsem commented
Replaced by #12830

2019-09-17 08:23 UTC, closed without merging