feat(cache): wip
Elgg/Elgg pull request #12902
Opened 2019-11-05 16:41 UTC by jeabakker

2019-11-21 08:37 UTC, jdalsem requested changes

2019-11-21 08:37 UTC, jdalsem commented on docs/design/events.rst
> +Instead of triggering the ``:before`` and ``:after`` event manually, its possible to trigger an event sequence. This will trigger
it's

2019-11-21 08:37 UTC, jdalsem commented on docs/design/events.rst
> +the ``:before`` event, than the actual event and finaly the ``:after`` event.
then... finally

2019-11-21 08:37 UTC, jdalsem commented on docs/design/events.rst
> +When called with for exampe ``'cache:clear', 'system'`` the following three events are triggered
example

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Cache/CompositeCache.php
> +		// because Stash assumes all files/folder as made by Stash
are*

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Cache/CompositeCache.php
> +		// because Stash assumes all files/folder as made by Stash
folders*

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Cache/SimpleCache.php
> +		$this->config->save('simplecache_lastupdate', time());
add @todo remove in 4.0

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Cache/SystemCache.php
> +		$cached_data = $this->cache->load($type, null);
Why was this needed?

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Config.php
> + * @property int           $lastcache								The timestamp the cache was last invalidated/cleared
remove 'cleared'

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/EventsService.php
> -	 * @see elgg_trigger_deprecated_event()
huh? it still applies here i guess

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/EventsService.php
> +	 * @see elgg_trigger_deprecated_event()
probably should have removed this

2019-11-21 08:37 UTC, jdalsem commented on engine/classes/Elgg/Cache/SimpleCache.php
> +	public function invalidate(bool $include_clear = null) {
add @todo to remove `include_clear` param in 4.0

2019-11-22 08:18 UTC, jeabakker commented on engine/classes/Elgg/Cache/SystemCache.php
> +		$cached_data = $this->cache->load($type, null);
left over, oops

2019-11-22 08:19 UTC, jeabakker commented on engine/classes/Elgg/EventsService.php
> -	 * @see elgg_trigger_deprecated_event()
done

2019-11-22 08:19 UTC, jeabakker commented on engine/classes/Elgg/EventsService.php
> +	 * @see elgg_trigger_deprecated_event()
indeed

2019-11-22 09:24 UTC, merged