Annotation and user subviews
Elgg/Elgg pull request #12980
Opened 2019-12-19 14:41 UTC by jeabakker

2019-12-19 17:28 UTC, jdalsem requested changes

2019-12-19 17:28 UTC, jdalsem commented on views/default/annotation/elements/summary/content.php
> +
if content empty return

2019-12-19 17:28 UTC, jdalsem commented on views/default/annotation/elements/summary/icon.php
> +if ($icon !== '') {
?? maybe duplicate code?

2019-12-19 17:28 UTC, jdalsem commented on views/default/annotation/elements/summary/subtitle.php
> +	$subtitle = '';
not needed

2019-12-19 17:28 UTC, jdalsem commented on views/default/annotation/elements/summary/title.php
> +	]);
wrap in h3? check with likes

2019-12-19 17:28 UTC, jdalsem commented on views/default/user/elements/imprint.php
> + * Displays information about the location and brief description of the user
no it doesnt

2019-12-19 17:28 UTC, jdalsem commented on views/default/user/elements/imprint/briefdescription.php
> +if (!isset($time)) {
uh time/?

2019-12-19 17:28 UTC, jdalsem commented on views/default/user/elements/imprint/contents.php
> + * Displays information about the author, the time and the access of the post
update text

2019-12-19 17:28 UTC, jdalsem commented on views/default/user/elements/summary/content.php
> +		$content = elgg_view('user/status', $vars);
should we only pass entity?

2019-12-20 10:08 UTC, jeabakker commented on views/default/annotation/elements/summary/icon.php
> +if ($icon !== '') {
fixed

2019-12-20 10:08 UTC, jeabakker commented on views/default/annotation/elements/summary/content.php
> +
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/annotation/elements/summary/subtitle.php
> +	$subtitle = '';
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/annotation/elements/summary/title.php
> +	]);
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/user/elements/imprint.php
> + * Displays information about the location and brief description of the user
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/user/elements/imprint/briefdescription.php
> +if (!isset($time)) {
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/user/elements/imprint/contents.php
> + * Displays information about the author, the time and the access of the post
fixed

2019-12-20 10:09 UTC, jeabakker commented on views/default/user/elements/summary/content.php
> +		$content = elgg_view('user/status', $vars);
fixed

2019-12-20 11:04 UTC, jdalsem requested changes

2019-12-20 11:06 UTC, jeabakker commented on views/default/annotation/elements/imprint/contents.php
> + * Displays imprint contents
fixed

2019-12-20 11:23 UTC, jdalsem approved these changes

2019-12-20 11:23 UTC, merged