Cli single upgrade
Elgg/Elgg pull request #13018
Opened 2020-01-15 13:51 UTC by jdalsem

2020-01-15 14:19 UTC, jeabakker requested changes

2020-01-15 14:19 UTC, jeabakker commented on engine/tests/phpunit/integration/Elgg/Cli/UpgradeBatchCommandTest.php
> +		$this->assertRegExp('/' . elgg_echo('cli:upgrade:batch:finished') . '/im', $commandTester->getDisplay());
you can also use `->assertStringContains()`

2020-01-15 14:19 UTC, jeabakker commented on engine/classes/Elgg/Cli/UpgradeBatchCommand.php
> +use Symfony\Component\Console\Input\InputArgument;
left over junk

2020-01-15 14:19 UTC, jeabakker commented on engine/tests/phpunit/integration/Elgg/Upgrade/LocatorIntegrationTest.php
> +}
aaaarrrrhhhh, luck for you the lint tests don't work on tests

2020-01-16 14:32 UTC, jdalsem commented
do not merge yet... additional feat coming

2020-01-21 15:20 UTC, jeabakker approved these changes

2020-01-21 15:20 UTC, merged