3.3 plugin features
Elgg/Elgg pull request #13015
Opened 2020-01-14 11:42 UTC by jdalsem

2020-01-14 13:48 UTC, jeabakker requested changes
no tests yet??

2020-01-14 13:48 UTC, jeabakker commented on engine/classes/Elgg/Composer/PostInstall.php
> +		return !is_dir($from) && symlink($to, $from);
wrong advise from me, please revert this

2020-01-14 13:48 UTC, jeabakker commented on engine/classes/ElggPlugin.php
> +				elgg_deprecated_notice("Using a start file in your plugin [{$this->getID()}] is deprecated. Use a elgg-plugin.php or PluginBootstrap class for your plugin.", '3.3');
using a start.php ....

2020-01-15 10:03 UTC, jdalsem commented
Created https://github.com/Elgg/Elgg/issues/13014 to add more tests for elgg-plugin.php features

2020-01-15 10:06 UTC, jeabakker approved these changes

2020-01-15 10:06 UTC, merged