Feature/js add smtp support
Elgg/Elgg pull request #13030
Opened 2020-01-19 13:08 UTC by NerdsvilleCEO

Solves #12938 

Notes:
  - Email from address should be configured in admin interface (I assume this is a non-issue as this seems to be necessary for sendmail as well)
  - SMTP configuration must be made in order for this to work correctly (how should we handle errors, or should we trust the user reads the comments in settings?)
  - This is my first PR to the codebase so I probably did something wrong, please be critical on review :)

2020-01-21 08:40 UTC, jeabakker requested changes
Just a few minor remarks.
Also have a look at http://learn.elgg.org/en/stable/contribute/code.html#commit-message-format for the correct format of the commit message.
Something like `feat(mail): add smtp support`

2020-01-21 08:40 UTC, jeabakker commented on elgg-config/settings.example.php
> + * Currently only 'smtp' and 'sendmail' is supported as a different configuration.
... 'sendmail' **are** supported

2020-01-21 08:40 UTC, jeabakker commented on engine/classes/Elgg/Config.php
> + * @property string        $emailer_transport
please add a description, for future reference

2020-01-21 08:40 UTC, jeabakker commented on engine/classes/Elgg/Config.php
> + * @property array         $emailer_smtp_settings
please add a description, for future reference

2020-01-21 09:28 UTC, jeabakker commented
I thought of some more remarks
- since this is a feature it needs to be on the `3.x` branch. 
You'll need to rebase your working branch
- if possible squash all the commits into a single one

2020-01-22 14:30 UTC, jdalsem commented
Is this tested with a working SMTP server? Or is it an assumption that this solutions should work?

2020-01-22 19:52 UTC, NerdsvilleCEO commented
@jdalsem yes it's tested on an actual SMTP server. I tested with mailgun (try to avoid making PR's without testing :))

If someone other than me wants to volunteer to test it that'd be great to make sure my settings are understandable etc and things work for them.

Working on the changes now, apologies for the delay I'm in the hospital taking care of family.

2020-01-23 07:51 UTC, jeabakker approved these changes

2020-01-23 07:52 UTC, jeabakker commented
The only problem is the format of the commit message, but we can fix that during merge

2020-01-23 08:20 UTC, merged

2020-01-23 08:20 UTC, jdalsem commented
Thanks man!