feat(forms): entityt field config can be requested from a service
Elgg/Elgg pull request #13478
Opened 2021-05-11 09:24 UTC by jdalsem

fixes #13372

2021-05-11 11:17 UTC, jeabakker requested changes

2021-05-11 11:22 UTC, jeabakker commented on engine/classes/Elgg/Forms/FieldsService.php
> +				continue;
log warning

2021-05-12 12:47 UTC, jdalsem commented on mod/pages/views/default/forms/pages/edit.php
> +	$field['value'] = $vars[$name];
ok

2021-05-12 12:48 UTC, jdalsem commented on engine/classes/Elgg/Forms/FieldsService.php
> +				continue;
done

2021-05-12 15:05 UTC, jeabakker requested changes

2021-05-12 15:09 UTC, jeabakker approved these changes

2021-05-12 15:22 UTC, merged