feat(search): moved result formatting logic into views
Elgg/Elgg pull request #13493
Opened 2021-05-20 14:23 UTC by jdalsem

- [x] rss view
- [x] rename comment hook

2021-05-20 14:23 UTC, jdalsem commented on mod/search/views/default/search/elements/content.php
> + *   - search_matched_title (defaults to entity->getDisplay())
incorrect

2021-05-20 14:24 UTC, jdalsem commented on mod/search/views/default/search/elements/icon.php
> +	echo elgg_view_entity_icon($entity, $size);
is this intended? should it not be container entity?

2021-05-21 08:55 UTC, jeabakker requested changes

2021-05-21 08:55 UTC, jeabakker commented on mod/search/views/default/search/elements/icon.php
> +	return $entity->getVolatileData('search_icon');
shouldn't this be a `echo` and then `return`

2021-05-21 08:55 UTC, jeabakker commented on mod/search/views/default/search/elements/icon.php
> +} else if ($entity->getContainerEntity() instanceof ElggUser) {
why can't the container be a `group`?

2021-05-21 09:37 UTC, jdalsem commented on mod/search/views/default/search/elements/icon.php
> +} else if ($entity->getContainerEntity() instanceof ElggUser) {
it can but is was not

2021-05-21 09:37 UTC, jdalsem commented on mod/search/views/default/search/elements/icon.php
> +	echo elgg_view_entity_icon($entity, $size);
nope...

2021-05-21 09:38 UTC, jeabakker approved these changes

2021-05-21 09:38 UTC, merged