feat(cache): replaced stash with phpfastcache
Elgg/Elgg pull request #13885
Opened 2022-01-18 15:03 UTC by jdalsem

fixes #13770

2022-01-19 15:02 UTC, jeabakker requested changes

2022-01-19 15:02 UTC, jeabakker commented on engine/vendor_classes/Phpfastcache/Core/Item/ItemExtendedTrait.php
> +<?php
why was this class overruled?

2022-01-19 15:02 UTC, jeabakker commented on engine/vendor_classes/Phpfastcache/Util/ArrayObject.php
> +<?php
why was this class overruled?

2022-01-19 15:05 UTC, jdalsem commented on engine/classes/Elgg/Cache/CompositeCache.php
> +		return str_replace(['{', '}', '(', ')', '/', '\\', '@', ':'], '_', "{$key}");
keeping this inline with the validation in phpfastcache

2022-01-20 14:59 UTC, jeabakker approved these changes

2022-01-21 09:23 UTC, jeabakker approved these changes

2022-01-21 09:23 UTC, merged