feat(entities): add generic sort options
Elgg/Elgg pull request #13984
Opened 2022-04-14 15:42 UTC by jeabakker

2022-04-19 15:04 UTC, jdalsem requested changes

2022-04-19 15:04 UTC, jdalsem commented on views/json/resources/livesearch/groups.php
> +		'property_value' => 'name',
property

2022-04-20 08:09 UTC, jeabakker commented on docs/guides/search.rst
> +        'sort_by' => [[
added

2022-04-20 08:10 UTC, jeabakker commented on engine/classes/Elgg/Menus/FilterSortItems.php
> +			return null;
the new standard is to have typehinted return values on all functions

2022-04-20 08:11 UTC, jeabakker commented on engine/classes/Elgg/Menus/FilterSortItems.php
> +				'sort_by' => [[
fixed

2022-04-20 08:11 UTC, jeabakker commented on engine/classes/Elgg/Menus/Page.php
> +			'href' => 'admin/usersasudfhgaisdgfiau',
oops ;)

2022-04-20 08:13 UTC, jeabakker commented on engine/hooks.php
> +			'Elgg\Menus\Page::prepareAdminAdminister' => [],
changed

2022-04-20 08:14 UTC, jeabakker commented on engine/lib/entities.php
> + * 			'property_type' => 'private_setting',
yep ;)

2022-04-20 08:16 UTC, jeabakker commented on mod/groups/classes/Elgg/Groups/Menus/FilterSortItems.php
> +	public static function registerMembershipSorting(\Elgg\Hook $hook): ?MenuItems {
keeping this inline with the core FilterSortItems

2022-04-20 08:17 UTC, jeabakker commented on mod/search/classes/Elgg/Search/Search.php
> +			'sort' => $sort, // deprecated
Is handled in the ``Elgg\Search\SearchService``

2022-04-20 08:18 UTC, jeabakker commented on views/json/resources/livesearch/groups.php
> +		'property_value' => 'name',
fixed

2022-04-20 08:18 UTC, jeabakker commented on views/json/resources/livesearch/objects.php
> +		'property_value' => 'title',
fixed

2022-04-20 08:18 UTC, jeabakker commented on views/json/resources/livesearch/users.php
> +		'property_value' => 'name',
done and fixed

2022-04-20 08:20 UTC, jeabakker commented on engine/classes/Elgg/Database/Clauses/EntitySortByClause.php
>  				if (!in_array($this->property, ElggEntity::PRIMARY_ATTR_NAMES)) {
agree, but not changing this. It's documented that not all sort features might work on non ``elgg_get_entities`` functions

2022-04-20 09:23 UTC, jdalsem approved these changes

2022-04-20 09:24 UTC, jdalsem approved these changes

2022-04-20 10:37 UTC, merged