4.2.0 fixes
Elgg/Elgg pull request #14019
Opened 2022-05-17 13:41 UTC by jdalsem

2022-05-17 13:54 UTC, jeabakker requested changes

2022-05-17 13:56 UTC, jdalsem commented on mod/blog/views/default/elgg/blog/save_draft.js
>  define(['jquery', 'elgg', 'elgg/Ajax', 'elgg/i18n'], function($, elgg, Ajax, i18n) {
nope

2022-05-17 14:00 UTC, jeabakker approved these changes

2022-05-19 11:34 UTC, jeabakker approved these changes

2022-05-19 11:35 UTC, merged