fix(notifications): handle exceptions during notification processing
Elgg/Elgg pull request #14068
Opened 2022-07-05 07:27 UTC by jeabakker

fixes #13699

2022-07-05 10:01 UTC, jdalsem commented on views/default/email/elements/body.php
> + * @uses $vars['email']    the \Elgg\Email which is being processed
why not document 'add_mute_link'?

2022-07-05 10:03 UTC, jdalsem commented on views/default/email/elements/body.php
> + * @uses $vars['email']    the \Elgg\Email which is being processed
probably because it is not part of the 'vars' :)

2022-07-05 14:00 UTC, jdalsem requested changes

2022-07-05 14:05 UTC, jeabakker commented on engine/classes/Elgg/AuthenticationService.php
> +		return true;
would be inline with hooks/event registration (and previous code)

2022-07-05 14:09 UTC, jeabakker commented on engine/lib/pam.php
> +	return _elgg_services()->authentication->registerHandler($handler, $importance, $policy);
nope

2022-07-06 07:15 UTC, jeabakker commented on mod/web_services/classes/Elgg/WebServices/ApiMethods/AuthGetToken.php
>  		throw new SecurityException(elgg_echo('SecurityException:authenticationfailed'));
keeping as is

2022-07-06 07:15 UTC, jeabakker commented on mod/web_services/classes/Elgg/WebServices/RestServiceController.php
> +			throw new \APIException($message, \ErrorResult::$RESULT_FAIL_AUTHTOKEN);
keeping as is

2022-07-06 11:33 UTC, jdalsem requested changes

2022-07-06 11:33 UTC, jdalsem commented on engine/lib/pam.php
> + * they are registered. For an example of a PAM, see \Elgg\PAM\Password.
namespace

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/classes/Elgg/WebServices/PAM/APIHmac.php
> +namespace Elgg\WebServices\PAM;
namespace in api

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/classes/Elgg/WebServices/PAM/UserToken.php
> +namespace Elgg\WebServices\PAM;
namespace + class rename

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/classes/Elgg/WebServices/PAM/UserToken.php
> +		if (!login($user)) {
return login() or try/catch as it can throw

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/classes/Elgg/WebServices/PAM/APIKey.php
> +namespace Elgg\WebServices\PAM;
namespace + rename class

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/tests/phpunit/integration/Elgg/WebServices/ElggCoreWebServicesApiTest.php
> +use Elgg\WebServices\PAM\APIKey;
namespace

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/tests/phpunit/integration/Elgg/WebServices/ElggCoreWebServicesApiTest.php
> +		$apikey();
wth?

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/tests/phpunit/integration/Elgg/WebServices/ElggCoreWebServicesApiTest.php
> +		$apikey();
weird science

2022-07-06 11:33 UTC, jdalsem commented on mod/web_services/tests/phpunit/integration/Elgg/WebServices/ElggCoreWebServicesApiTest.php
> +		$apikey = new APIKey();
namespace

2022-07-06 11:48 UTC, jeabakker commented on mod/web_services/tests/phpunit/integration/Elgg/WebServices/ElggCoreWebServicesApiTest.php
> +		$apikey();
sorry ;)

2022-07-06 12:33 UTC, merged