widget more links
Elgg/Elgg pull request #14071
Opened 2022-07-05 13:27 UTC by jdalsem

2022-07-05 13:59 UTC, jeabakker requested changes

2022-07-05 13:59 UTC, jeabakker commented on mod/blog/views/default/widgets/blog/content.php
> +	$url = elgg_generate_url('collection:object:bookmarks:all');
wrong plugin ;)

2022-07-05 13:59 UTC, jeabakker commented on mod/file/views/default/widgets/filerepo/content.php
>  } else {
don't we need to check if owner is a ElggUser

2022-07-05 13:59 UTC, jeabakker commented on mod/discussions/views/default/widgets/discussions/content.php
>  }
else link to all discussions?

2022-07-05 13:59 UTC, jeabakker commented on mod/file/views/default/widgets/filerepo/content.php
>  } else {
and have a case to link to all files?

2022-07-05 13:59 UTC, jeabakker commented on views/default/output/url.php
> +	var_dump($vars);
oops

2022-07-05 13:59 UTC, jeabakker commented on mod/groups/views/default/groups/profile/module.php
> +		$footer = elgg_format_element('span', ['class' => 'elgg-more'], $add_link);
wouldn't it be nicer to use the `page/components/list/widget_more` view

2022-07-05 13:59 UTC, jeabakker commented on mod/groups/views/default/groups/profile/module.php
> +		$footer = elgg_format_element('span', ['class' => 'elgg-more'], $add_link);
because of consistent styling if the view is overruled

2022-07-05 13:59 UTC, jeabakker commented on mod/groups/views/default/widgets/a_users_groups/content.php
> +$more_link = elgg_view_url(elgg_generate_url('collection:group:group:member', ['username' => $owner->username]), elgg_echo('groups:more'));
sure `$owner` is an ElggUser?

2022-07-05 13:59 UTC, jeabakker commented on mod/messageboard/views/default/widgets/messageboard/content.php
> +$more_link = elgg_view_url(elgg_generate_url('collection:annotation:messageboard:owner', ['username' => $owner->username]), elgg_echo('link:view:all'));
sure `$owner` is an ElggUser?

2022-07-05 13:59 UTC, jeabakker commented on mod/search/views/default/search/list.php
>  	]);
shouldn't this be the page element view?

2022-07-06 07:30 UTC, jdalsem commented on mod/groups/views/default/widgets/a_users_groups/content.php
> +$more_link = elgg_view_url(elgg_generate_url('collection:group:group:member', ['username' => $owner->username]), elgg_echo('groups:more'));
no... but wont die on it

2022-07-06 09:58 UTC, jeabakker approved these changes

2022-07-06 10:22 UTC, merged