feat(db): private settings are merged into metadata
Elgg/Elgg pull request #14137
Opened 2022-08-25 07:24 UTC by jdalsem

fixes #13881

2022-08-29 12:24 UTC, jeabakker requested changes

2022-08-29 13:26 UTC, jdalsem commented on engine/classes/Elgg/Traits/Entity/PluginSettings.php
> +		return $this->setMetadata($name, $value);
nope need to return a status

2022-08-29 13:26 UTC, jdalsem commented on engine/classes/Elgg/Traits/Entity/PluginSettings.php
> +		return $this->getMetadata($name) ?? $default;
nope need to return a status

2022-08-29 13:26 UTC, jdalsem commented on engine/classes/Elgg/Traits/Entity/PluginSettings.php
> +		return $this->deleteMetadata($name);
nope need to return a status

2022-08-30 11:34 UTC, jdalsem commented
Replaced by #14143

2022-08-30 11:34 UTC, closed without merging