chore(core): typehinting more of the core libs
Elgg/Elgg pull request #14150
Opened 2022-09-05 08:48 UTC by jdalsem

2022-09-06 12:31 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Views/ViewRenderingTestCase.php
> +			case 'forms' :
lol.. these were never correct...

2022-09-20 09:24 UTC, jeabakker requested changes
also loot at your own todo

2022-09-20 09:24 UTC, jeabakker commented on engine/classes/ElggEntity.php
> +			throw new ElggInvalidArgumentException(__METHOD__ . ' requires $subtype to be non empty');
exception not documented

2022-09-20 09:24 UTC, jeabakker commented on engine/lib/river.php
> +
please insert below file description

2022-09-20 09:24 UTC, jeabakker commented on engine/lib/river.php
> +
also make this an alias like ``ElggInvalidArgumentException`` to prevent notices from Scrutinizer

2022-09-20 09:24 UTC, jeabakker commented on engine/lib/river.php
> +		throw new InvalidArgumentException(__METHOD__ . ' requires at least one of the following keys in $options: ' . implode(', ', $required));
and use the alias here

2022-09-20 09:24 UTC, jeabakker commented on engine/lib/river.php
> + * @throws InvalidArgumentException
document the namespaced exception pleae to prevent confusion

2022-09-20 09:24 UTC, jeabakker commented on engine/tests/phpunit/integration/Elgg/Integration/ElggCoreRiverAPITest.php
> +use Elgg\Exceptions\InvalidArgumentException;
order ;)

2022-09-20 09:24 UTC, jeabakker commented on mod/pages/classes/ElggPage.php
> +	 * @return ElggPage|null
``\ElggPage``

2022-09-20 09:24 UTC, jeabakker commented on mod/pages/classes/ElggPage.php
> +		return $parent instanceof ElggPage ? $parent : null;
``\ElggPage``

2022-09-20 14:17 UTC, jeabakker approved these changes

2022-09-20 14:17 UTC, merged