feat(forms): automatically support stick forms
Elgg/Elgg pull request #14213
Opened 2022-11-17 14:57 UTC by jeabakker

fixes #11141

2022-11-18 07:56 UTC, jdalsem requested changes
also a sticky typo in your commit message :)

2022-11-18 07:56 UTC, jdalsem commented on docs/guides/events-list.rst
> +	Sticky form values will automaticly be added to the field values (when available).
automatically

2022-11-18 07:56 UTC, jdalsem commented on engine/classes/Elgg/Router/Middleware/ActionMiddleware.php
> +		$form_name = $this->request->getParam('_elgg_sticky_form_name');
need to check if not empty... could be removed somewhere in between...

2022-11-22 10:04 UTC, jdalsem requested changes

2022-11-22 10:09 UTC, jeabakker commented on views/default/resources/index.php
> +		'sticky_enabled' => true,
maybe not, but keeping all registration forms inline with each other

2022-11-22 10:12 UTC, jeabakker commented on engine/classes/Elgg/Router/Middleware/ActionMiddleware.php
> +		$ignored_fields = array_merge($ignored_fields, ['_elgg_sticky_form_name', '_elgg_sticky_ignored_fields', '_route']);
moved

2022-11-22 10:35 UTC, jdalsem approved these changes

2022-11-22 10:42 UTC, jeabakker commented on engine/tests/phpunit/integration/Elgg/Forms/StickyFormsIntegrationTest.php
> +			'_elgg_sticky_form_name' => 'foo', // added by sticky form support
not in this test ;)

2022-11-22 10:42 UTC, merged