chore(core): PHP 8.2 compatibility
Elgg/Elgg pull request #14238
Opened 2022-11-28 12:48 UTC by jeabakker

ref #14237

2022-11-28 15:33 UTC, jdalsem requested changes

2022-11-28 15:33 UTC, jdalsem commented on engine/classes/Elgg/Exceptions/PluginException.php
> +	 * @var \ElggPlugin|null
no need

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/classes/Elgg/Helpers/Collections/TestItem.php
> +	protected $id;
type hint attributes and remove docs

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Database/Clauses/AccessWhereClauseIntegrationTest.php
> +	protected $user;
type hint attribute (nullable)

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Integration/ElggCoreMetastringsTest.php
> +	protected $object;
type hint

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Integration/ElggCoreMetastringsTest.php
> +	protected $object;
and nullable

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Navigation/MenuRenderingIntegrationTest.php
> +	protected $user;
atrtibutes type hints and nullables

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Notifications/NotificationsServiceIntegrationTestCase.php
> +	protected $session_manager;
typehinting

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Views/DateOutputTest.php
> +	protected $date;
typehinting

2022-11-28 15:33 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Security/UrlSignerUnitTest.php
> +	protected $service;
typehinting

2022-12-01 15:05 UTC, jeabakker commented
maybe/probably I haven't found all English translations in other translations, but I found a lot

2022-12-05 09:17 UTC, jdalsem approved these changes

2022-12-05 13:47 UTC, jdalsem approved these changes

2022-12-05 13:53 UTC, merged