chore(views): split userpicker into entity picker
Elgg/Elgg pull request #14409
Opened 2023-07-06 15:13 UTC by jdalsem

fixes #14399

2023-07-07 09:02 UTC, jdalsem commented on views/default/input/userpicker.php
> -	'class' => 'elgg-input-user-picker',
replacing this class could cause issues... should we add it back (maybe via an extra view var)

2023-07-07 09:03 UTC, jdalsem commented on views/default/input/userpicker.php
> -	'class' => 'elgg-input-user-picker',
maybe just hardcoded adding it for BC purposes with a deprecated notice for future cleanup might be better

2023-07-10 08:24 UTC, jeabakker requested changes

2023-07-10 08:24 UTC, jeabakker commented on views/default/elements/components/userpicker.css
> +	USER PICKER This view is deprecated and replaced by elements/components/entitypicker
isn't it replaced by ``input/entitypicker.css``

2023-07-10 09:52 UTC, jeabakker approved these changes

2023-07-10 10:10 UTC, merged