Features
Elgg/Elgg pull request #14489
Opened 2023-10-20 08:22 UTC by jeabakker

2023-10-20 14:30 UTC, jdalsem requested changes

2023-10-20 14:30 UTC, jdalsem commented on views/default/elgg/comments.js
> +			// this.getForm().find('.elgg-field-input:first > textarea').show().focus();
oops

2023-10-23 08:07 UTC, jeabakker commented on views/default/elgg/comments.js
> +			// this.getForm().find('.elgg-field-input:first > textarea').show().focus();
fixed it

2023-10-23 09:54 UTC, jdalsem approved these changes

2023-10-23 09:54 UTC, merged