chore(composer): minimal PHP version is now 8.1
Elgg/Elgg pull request #14532
Opened 2023-12-01 11:04 UTC by jdalsem

Also we now fully support PHP 8.3

2023-12-01 11:12 UTC, jeabakker approved these changes

2024-01-16 10:22 UTC, jeabakker requested changes

2024-01-16 10:22 UTC, jeabakker commented on engine/tests/phpunit/unit/Elgg/RouterUnitTest.php
> +
????

2024-01-16 10:22 UTC, jeabakker commented on engine/tests/phpunit/unit/Elgg/Users/AccountsServiceUnitTest.php
> +	protected const minusername = 6;
constants should be uppercase

2024-01-16 12:11 UTC, jdalsem commented on engine/tests/classes/Elgg/BaseTestCase.php
> +		if (CompositeCache::isMemcacheAvailable()) {
talked about it, not going to check it

2024-01-16 13:55 UTC, jeabakker requested changes

2024-01-16 13:55 UTC, jeabakker commented on engine/tests/classes/Elgg/BaseTestCase.php
> +		foreach (CacheManager::getInstances() as $instance ){
`$instance ){` => `$instance) {`

2024-01-16 14:19 UTC, jeabakker approved these changes

2024-01-16 14:28 UTC, merged