fix(database): allow both metadata and annotations
Elgg/Elgg pull request #14535
Opened 2023-12-01 15:03 UTC by jeabakker

fixes #14405

2023-12-19 13:39 UTC, jdalsem requested changes

2023-12-19 13:39 UTC, jdalsem commented on engine/classes/Elgg/Database/Repository.php
>  	 * @param mixed  $y              Comparison value(s)
if changing x why not y

2023-12-19 13:39 UTC, jdalsem commented on engine/classes/Elgg/Database/River.php
> +	 * @return array|\ElggData[]|\ElggEntity[]|int|\ElggBatch
check

2023-12-19 13:39 UTC, jdalsem commented on engine/classes/Elgg/Upgrades/NotificationsPrefix.php
> +				->where($select->compare("{$select->getTableAlias()}.guid_one", '=', 'r2.guid_one'))
r2 alias (2 lines)

2023-12-19 13:39 UTC, jdalsem commented on engine/classes/ElggSite.php
>  		$db = $this->getDatabase();
no need to put $db in a variable

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Integration/ElggCoreGetEntitiesFromAnnotationsTest.php
> +				new WhereClause("CAST(a_table.value as DECIMAL(10, 2)) > 0"),
why not const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/integration/Elgg/Integration/ElggCoreGetEntitiesFromAnnotationsTest.php
> +					new WhereClause("CAST(a_table.value AS DECIMAL(10, 2)) > 0"),
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
should `e` alias come from a const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
same

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +				new OrderByClause('a_table.id', 'ASC'),
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +				new OrderByClause('a_table.id', 'ASC'),
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +				'a_table.entity_guid',
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
const e?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +				new OrderByClause('a_table.id', 'ASC'),
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
const e?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
>  		$select->addClause(new EntityWhereClause(), 'e');
const?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/AnnotationsUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
const? maybe search for `'e'` in whole file...

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/Clauses/AccessWhereClauseUnitTest.php
> -use ElggUser;
maybe (other PR) do a pass for all unwanted root classes with a use...

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/Clauses/WhereClauseUnitTest.php
> +		$expected = $this->qb->compare("{{$this->qb->getTableAlias()}}.guid", '=', 25, ELGG_VALUE_INTEGER);
too much accolades

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/Clauses/WhereClauseUnitTest.php
> +			return $qb->compare("{{$this->qb->getTableAlias()}}.guid", '=', 25, ELGG_VALUE_INTEGER);
too much accolades

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/MetadataUnitTest.php
> +		$select->join($select->getTableAlias(), 'entities', 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
const entiteis and const e?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/MetadataUnitTest.php
> +		$select->join($select->getTableAlias(), EntityTable::TABLE_NAME, 'e', "e.guid = {$select->getTableAlias()}.entity_guid");
ha... a partial const :)

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/RelationshipsUnitTest.php
> +		$select->joinEntitiesTable($select->getTableAlias(), 'guid_one', 'inner', 'e');
const e?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/RelationshipsUnitTest.php
> +		$select->join($select->getTableAlias(), MetadataTable::TABLE_NAME, 'n_table', "{$select->getTableAlias()}.guid_one = n_table.entity_guid");
const n_table?

2023-12-19 13:39 UTC, jdalsem commented on engine/tests/phpunit/unit/Elgg/Database/RelationshipsUnitTest.php
> +		$select->select('min(a_table.value) AS calculation');
no const a_table?

2023-12-19 13:39 UTC, jdalsem commented on mod/blog/views/default/blog/sidebar/revisions.php
> +		new OrderByClause('a_table.time_created', 'DESC'),
was there no sort_by alternative approach?

2023-12-19 13:39 UTC, jdalsem commented on mod/likes/views/default/likes/popup.php
> +	'order_by' => new OrderByClause('a_table.time_created', 'desc'),
sort by?

2023-12-19 13:39 UTC, jdalsem commented on mod/messageboard/actions/messageboard/add.php
> +		new OrderByClause('a_table.time_created', 'DESC'),
sort by?

2023-12-19 13:39 UTC, jdalsem commented on mod/messageboard/views/default/resources/messageboard/owner.php
> +		new OrderByClause('a_table.time_created', 'DESC'),
sort by?

2023-12-19 13:39 UTC, jdalsem commented on mod/messageboard/views/default/widgets/messageboard/content.php
> +		new OrderByClause('a_table.time_created', 'DESC'),
sort by?

2023-12-19 13:39 UTC, jdalsem commented on mod/pages/views/default/pages/sidebar/history.php
> +			new OrderByClause('a_table.time_created', 'desc'),
sort by?

2023-12-19 13:39 UTC, jdalsem commented on mod/pages/views/default/resources/pages/history.php
> +		new OrderByClause('a_table.time_created', 'desc'),
sort by?

2023-12-19 13:48 UTC, jeabakker commented on engine/classes/Elgg/Database/Annotations.php
> +	 * @return array|\ElggData[]|\ElggAnnotation[]|int|\ElggBatch
true

2023-12-19 14:17 UTC, jeabakker commented on engine/classes/Elgg/Database/Annotations.php
> +				$joined_alias = $qb->joinMetadataTable($qb->getTableAlias(), 'entity_guid', null, 'inner', MetadataTable::DEFAULT_JOIN_ALIAS);
will not work to get join aliases like `qbt1` and therefore will cause conflicts in queries

2023-12-19 14:18 UTC, jeabakker commented on engine/classes/Elgg/Database/Annotations.php
> +				$joined_alias = $qb->joinRelationshipTable($qb->getTableAlias(), $join_on, null, $clause->inverse, 'inner', RelationshipsTable::DEFAULT_JOIN_ALIAS);
will not work to get join aliases like `qbt1` and therefore will cause conflicts in queries

2023-12-19 14:18 UTC, jeabakker commented on engine/classes/Elgg/Database/Annotations.php
> +		$joined_alias = $qb->joinEntitiesTable($qb->getTableAlias(), 'entity_guid', 'inner', EntityTable::DEFAULT_JOIN_ALIAS);
will not work to get join aliases like `qbt1` and therefore will cause conflicts in queries

2023-12-19 14:21 UTC, jeabakker commented on engine/classes/Elgg/Database/Entities.php
> +			if (strtoupper($boolean) === 'OR' || count($clauses) === 1) {
nope, discussed

2023-12-19 14:28 UTC, jeabakker commented on engine/classes/Elgg/Database/Metadata.php
> +		$qb->select("{$distinct} {$qb->getTableAlias()}.*");
no idea,  fixed

2023-12-19 14:32 UTC, jeabakker commented on engine/classes/Elgg/Database/RelationshipsTable.php
> +	public const RELATIONSHIP_COLUMN_LENGTH = 255;
yes used in 
https://github.com/Elgg/Elgg/blob/7a6f5487461e3f99ac8263b5f8ebacf96af78b82/engine/tests/phpunit/unit/Elgg/Database/RelationshipsTableUnitTest.php#L57

2023-12-19 14:35 UTC, jeabakker commented on engine/classes/Elgg/Database/Repository.php
>  	 * @param mixed  $y              Comparison value(s)
changed

2023-12-19 14:55 UTC, jeabakker commented on mod/blog/views/default/blog/sidebar/revisions.php
> +		new OrderByClause('a_table.time_created', 'DESC'),
no

2023-12-20 12:45 UTC, jeabakker commented on engine/classes/Elgg/Database/Metadata.php
>  			if (strtoupper($boolean) == 'OR' || count($clauses) > 1) {
fixed

2023-12-21 08:51 UTC, jdalsem approved these changes

2023-12-21 08:52 UTC, merged