fixed(core): correctly determine if plugins need reindexing
Elgg/Elgg pull request #14594
Opened 2024-04-03 15:03 UTC by jdalsem

2024-04-03 15:06 UTC, jdalsem commented on engine/classes/Elgg/Database/Plugins.php
> +			$priority = array_search($plugin_id, $order);
double check

2024-04-08 11:20 UTC, jeabakker requested changes

2024-04-08 11:20 UTC, jeabakker commented on engine/classes/Elgg/Database/Plugins.php
> +		return elgg_call(ELGG_IGNORE_ACCESS | ELGG_SHOW_DISABLED_ENTITIES, function() {
why not get the Invoker class through DI?

2024-04-08 11:20 UTC, jeabakker commented on engine/classes/Elgg/Database/Plugins.php
> +		$plugins = elgg_call(ELGG_IGNORE_ACCESS, function () use ($options) {
why not get the Invoker class through DI?

2024-04-15 07:32 UTC, jeabakker approved these changes

2024-04-15 07:33 UTC, merged